using UpgradeHelpers.Extensions;
using UpgradeHelpers.BasicViewModels.Extensions;
using UpgradeHelpers.Events;

namespace PTSProject.ViewModels
{

	[UpgradeHelpers.Helpers.Logic(Type = typeof(PTSProject.frmDailyStaffing))]
	public class frmDailyStaffingViewModel
		: UpgradeHelpers.Helpers.FormBaseViewModel
	{

		public override void Build(UpgradeHelpers.Interfaces.IIocContainer ctx)
		{
			base.Build(ctx);
			var textCellType30 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle72;
			FarPoint.ViewModels.NamedStyle namedStyle71;
			var textCellType29 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle70;
			FarPoint.ViewModels.NamedStyle namedStyle69;
			FarPoint.ViewModels.NamedStyle namedStyle68;
			var textCellType28 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle67;
			FarPoint.ViewModels.NamedStyle namedStyle66;
			var textCellType27 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle65;
			FarPoint.ViewModels.NamedStyle namedStyle64;
			var textCellType26 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle63;
			FarPoint.ViewModels.NamedStyle namedStyle62;
			var textCellType25 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle61;
			var textCellType24 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle60;
			FarPoint.ViewModels.NamedStyle namedStyle59;
			var textCellType23 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle58;
			var textCellType22 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle57;
			var textCellType21 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle56;
			FarPoint.ViewModels.NamedStyle namedStyle55;
			FarPoint.ViewModels.NamedStyle namedStyle54;
			var textCellType20 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle53;
			FarPoint.ViewModels.NamedStyle namedStyle52;
			FarPoint.ViewModels.NamedStyle namedStyle51;
			var textCellType19 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle50;
			FarPoint.ViewModels.NamedStyle namedStyle49;
			var textCellType18 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle48;
			var textCellType17 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle47;
			var textCellType16 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle46;
			FarPoint.ViewModels.NamedStyle namedStyle45;
			FarPoint.ViewModels.NamedStyle namedStyle44;
			var textCellType15 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle43;
			FarPoint.ViewModels.NamedStyle namedStyle42;
			var textCellType14 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle41;
			FarPoint.ViewModels.NamedStyle namedStyle40;
			FarPoint.ViewModels.NamedStyle namedStyle39;
			var textCellType13 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle38;
			FarPoint.ViewModels.NamedStyle namedStyle37;
			FarPoint.ViewModels.NamedStyle namedStyle36;
			FarPoint.ViewModels.NamedStyle namedStyle35;
			FarPoint.ViewModels.NamedStyle namedStyle34;
			FarPoint.ViewModels.NamedStyle namedStyle33;
			var textCellType12 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle32;
			FarPoint.ViewModels.NamedStyle namedStyle31;
			var textCellType11 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle30;
			FarPoint.ViewModels.NamedStyle namedStyle29;
			var textCellType10 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle28;
			FarPoint.ViewModels.NamedStyle namedStyle27;
			var textCellType9 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle26;
			FarPoint.ViewModels.NamedStyle namedStyle25;
			FarPoint.ViewModels.NamedStyle namedStyle24;
			FarPoint.ViewModels.NamedStyle namedStyle23;
			FarPoint.ViewModels.NamedStyle namedStyle22;
			FarPoint.ViewModels.NamedStyle namedStyle21;
			FarPoint.ViewModels.NamedStyle namedStyle20;
			FarPoint.ViewModels.NamedStyle namedStyle19;
			FarPoint.ViewModels.NamedStyle namedStyle18;
			FarPoint.ViewModels.NamedStyle namedStyle17;
			FarPoint.ViewModels.NamedStyle namedStyle16;
			var textCellType8 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle15;
			FarPoint.ViewModels.NamedStyle namedStyle14;
			var textCellType7 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle13;
			FarPoint.ViewModels.NamedStyle namedStyle12;
			var textCellType6 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle11;
			FarPoint.ViewModels.NamedStyle namedStyle10;
			FarPoint.ViewModels.NamedStyle namedStyle9;
			var textCellType5 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle8;
			FarPoint.ViewModels.NamedStyle namedStyle7;
			var textCellType4 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle6;
			var textCellType3 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle5;
			FarPoint.ViewModels.NamedStyle namedStyle4;
			var textCellType2 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle3;
			var textCellType1 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle2;
			FarPoint.ViewModels.NamedStyle namedStyle1;
			this.cboYear = ctx.Resolve<UpgradeHelpers.BasicViewModels.ComboBoxViewModel>();
			// 
			// cboYear
			// 
			this.cboYear.BackColor = UpgradeHelpers.Helpers.SystemColors.Window;
			this.cboYear.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10.5F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cboYear.ForeColor = UpgradeHelpers.Helpers.SystemColors.WindowText;
			this.cboYear.Name = "cboYear";
			this.cboYear.TabIndex = 9;
			this.cboMonth = ctx.Resolve<UpgradeHelpers.BasicViewModels.ComboBoxViewModel>();
			// 
			// cboMonth
			// 
			this.cboMonth.BackColor = UpgradeHelpers.Helpers.SystemColors.Window;
			this.cboMonth.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10.5F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cboMonth.ForeColor = UpgradeHelpers.Helpers.SystemColors.WindowText;
			this.cboMonth.Name = "cboMonth";
			this.cboMonth.TabIndex = 0;
			this.sprDaily = ctx.Resolve<FarPoint.ViewModels.FpSpreadViewModel>();
			this.sprDaily.MaxRows = 40;
			this.sprDaily.TabIndex = 10;
			this.sprDaily.TextTip = FarPoint.ViewModels.TextTipPolicy.Off;
			this.Label3 = ctx.Resolve<UpgradeHelpers.BasicViewModels.LabelViewModel>();
			// 
			// Label3
			// 
			this.Label3.BackColor = UpgradeHelpers.Helpers.Color.Transparent;
			this.Label3.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10.5F, UpgradeHelpers.Helpers.FontStyle.Bold, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.Label3.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
			this.Label3.Name = "Label3";
			this.Label3.TabIndex = 13;
			this.Label3.Text = "Report Year";
			this.Label2 = ctx.Resolve<UpgradeHelpers.BasicViewModels.LabelViewModel>();
			// 
			// Label2
			// 
			this.Label2.BackColor = UpgradeHelpers.Helpers.Color.Transparent;
			this.Label2.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10.5F, UpgradeHelpers.Helpers.FontStyle.Bold, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.Label2.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
			this.Label2.Name = "Label2";
			this.Label2.TabIndex = 12;
			this.Label2.Text = "Filter by Shift";
			this.Label1 = ctx.Resolve<UpgradeHelpers.BasicViewModels.LabelViewModel>();
			// 
			// Label1
			// 
			this.Label1.BackColor = UpgradeHelpers.Helpers.Color.Transparent;
			this.Label1.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10.5F, UpgradeHelpers.Helpers.FontStyle.Bold, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.Label1.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
			this.Label1.Name = "Label1";
			this.Label1.TabIndex = 11;
			this.Label1.Text = "Report Month";
			this.sprDaily_Sheet1 = ctx.Resolve<FarPoint.ViewModels.SheetViewModel>();
			this.sprDaily_Sheet1.SheetName = "Sheet1";
			this.sprDaily_Sheet1.Cells.Get(0, 0).Value = "Tacoma Fire Department";
			this.sprDaily_Sheet1.Cells.Get(1, 0).Value = "Daily Staffing Report";
			this.sprDaily_Sheet1.Cells.Get(2, 2).Value = "Working CSR";
			this.sprDaily_Sheet1.Cells.Get(2, 4).Value = "Working DD";
			this.sprDaily_Sheet1.Cells.Get(2, 6).Value = "Trainees";
			this.sprDaily_Sheet1.Cells.Get(2, 8).Value = "Working OT";
			this.sprDaily_Sheet1.Cells.Get(2, 10).Value = "Total Staffing";
			this.sprDaily_Sheet1.Cells.Get(2, 12).Value = "VAC-FHL-MIL";
			this.sprDaily_Sheet1.Cells.Get(2, 14).Value = "Sick Leave";
			this.sprDaily_Sheet1.Cells.Get(2, 16).Value = "Spec. Assign.";
			this.sprDaily_Sheet1.Cells.Get(2, 18).Value = "FCC";
			this.sprDaily_Sheet1.Cells.Get(2, 20).Value = "Actual Staffing";
			this.sprDaily_Sheet1.Cells.Get(3, 0).Value = "Date";
			this.sprDaily_Sheet1.Cells.Get(3, 1).Value = "Shf";
			this.sprDaily_Sheet1.Cells.Get(3, 2).Value = "AM";
			this.sprDaily_Sheet1.Cells.Get(3, 3).Value = "PM";
			this.sprDaily_Sheet1.Cells.Get(3, 4).Value = "AM";
			this.sprDaily_Sheet1.Cells.Get(3, 5).Value = "PM";
			this.sprDaily_Sheet1.Cells.Get(3, 6).Value = "AM";
			this.sprDaily_Sheet1.Cells.Get(3, 7).Value = "PM";
			this.sprDaily_Sheet1.Cells.Get(3, 8).Value = "AM";
			this.sprDaily_Sheet1.Cells.Get(3, 9).Value = "PM";
			this.sprDaily_Sheet1.Cells.Get(3, 10).Value = "AM";
			this.sprDaily_Sheet1.Cells.Get(3, 11).Value = "PM";
			this.sprDaily_Sheet1.Cells.Get(3, 12).Value = "AM";
			this.sprDaily_Sheet1.Cells.Get(3, 13).Value = "PM";
			this.sprDaily_Sheet1.Cells.Get(3, 14).Value = "AM";
			this.sprDaily_Sheet1.Cells.Get(3, 15).Value = "PM";
			this.sprDaily_Sheet1.Cells.Get(3, 16).Value = "AM";
			this.sprDaily_Sheet1.Cells.Get(3, 17).Value = "PM";
			this.sprDaily_Sheet1.Cells.Get(3, 18).Value = "AM";
			this.sprDaily_Sheet1.Cells.Get(3, 19).Value = "PM";
			this.sprDaily_Sheet1.Cells.Get(3, 20).Value = "AM";
			this.sprDaily_Sheet1.Cells.Get(3, 21).Value = "PM";
			this.sprDaily_Sheet1.Cells.Get(3, 22).Value = "Batt 1 BC";
			this.sprDaily_Sheet1.Cells.Get(3, 23).Value = "Batt 2 BC";
			this.sprDaily_Sheet1.Cells.Get(3, 24).Value = "Batt 3 BC";
			this.sprDaily_Sheet1.ColumnHeader.Rows.Get(0).Height = 0F;
			this.sprDaily_Sheet1.Columns.Get(0).Width = 52F;
			this.sprDaily_Sheet1.Columns.Get(1).StyleName = "Static814636234690624403326";
			this.sprDaily_Sheet1.Columns.Get(1).Width = 22F;
			this.sprDaily_Sheet1.Columns.Get(2).Width = 34F;
			this.sprDaily_Sheet1.Columns.Get(3).Width = 32F;
			this.sprDaily_Sheet1.Columns.Get(4).Width = 31F;
			this.sprDaily_Sheet1.Columns.Get(5).Width = 30F;
			this.sprDaily_Sheet1.Columns.Get(6).Width = 27F;
			this.sprDaily_Sheet1.Columns.Get(7).Width = 26F;
			this.sprDaily_Sheet1.Columns.Get(8).Width = 30F;
			this.sprDaily_Sheet1.Columns.Get(9).Width = 30F;
			this.sprDaily_Sheet1.Columns.Get(10).Width = 31F;
			this.sprDaily_Sheet1.Columns.Get(11).Width = 31F;
			this.sprDaily_Sheet1.Columns.Get(12).Width = 33F;
			this.sprDaily_Sheet1.Columns.Get(13).Width = 32F;
			this.sprDaily_Sheet1.Columns.Get(14).Width = 28F;
			this.sprDaily_Sheet1.Columns.Get(15).Width = 26F;
			this.sprDaily_Sheet1.Columns.Get(16).Width = 29F;
			this.sprDaily_Sheet1.Columns.Get(17).Width = 34F;
			this.sprDaily_Sheet1.Columns.Get(18).Width = 26F;
			this.sprDaily_Sheet1.Columns.Get(19).Width = 27F;
			this.sprDaily_Sheet1.Columns.Get(20).Width = 35F;
			this.sprDaily_Sheet1.Columns.Get(21).Width = 34F;
			this.sprDaily_Sheet1.Columns.Get(22).Width = 58F;
			this.sprDaily_Sheet1.Columns.Get(23).Width = 57F;
			this.sprDaily_Sheet1.Columns.Get(24).Width = 58F;
			this.sprDaily_Sheet1.RowHeader.Columns.Get(0).Width = 0F;
			this.sprDaily_Sheet1.Rows.Get(4).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(5).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(6).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(7).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(8).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(9).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(10).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(11).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(12).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(13).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(14).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(15).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(16).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(17).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(18).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(19).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(20).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(21).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(22).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(23).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(24).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(25).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(26).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(27).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(28).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(29).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(30).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(31).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(32).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(33).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(34).Height = 13F;
			this.sprDaily_Sheet1.Rows.Get(37).Height = 14F;
			this.cmdAnnualLeave = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdAnnualLeave
			// 
			this.cmdAnnualLeave.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdAnnualLeave.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.75F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdAnnualLeave.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdAnnualLeave.Name = "cmdAnnualLeave";
			this.cmdAnnualLeave.TabIndex = 14;
			this.cmdAnnualLeave.Text = "&Annual Leave Report";
			this.cmdOvertime = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdOvertime
			// 
			this.cmdOvertime.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdOvertime.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.75F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdOvertime.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdOvertime.Name = "cmdOvertime";
			this.cmdOvertime.TabIndex = 6;
			this.cmdOvertime.Text = "&Overtime Detail";
			this._cmdFilter_4 = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			this._cmdFilter_2 = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			this._cmdFilter_3 = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			this._cmdFilter_1 = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			this._cmdFilter_0 = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			this.cmdPrint = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdPrint
			// 
			this.cmdPrint.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdPrint.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.75F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdPrint.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdPrint.Name = "cmdPrint";
			this.cmdPrint.TabIndex = 7;
			this.cmdPrint.Text = "&Print";
			this.cmdClose = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdClose
			// 
			this.cmdClose.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdClose.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.75F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdClose.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdClose.Name = "cmdClose";
			this.cmdClose.TabIndex = 8;
			this.cmdClose.Text = "&Close";
			this.Text = "Daily Staffing Report";
			this.ThisMonth = 0;
			this.ThisYear = 0;
			this.CurrFilter = "";
			cmdFilter = ctx.Resolve<System.Collections.Generic.IList<UpgradeHelpers.BasicViewModels.ButtonViewModel>>(5);
			cmdFilter[4] = _cmdFilter_4;
			cmdFilter[2] = _cmdFilter_2;
			cmdFilter[3] = _cmdFilter_3;
			cmdFilter[1] = _cmdFilter_1;
			cmdFilter[0] = _cmdFilter_0;
			cmdFilter[4].BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			cmdFilter[4].Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.75F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			cmdFilter[4].ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			cmdFilter[4].Name = "_cmdFilter_4";
			cmdFilter[4].TabIndex = 5;
			cmdFilter[4].Text = "All";
			cmdFilter[2].BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			cmdFilter[2].Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.75F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			cmdFilter[2].ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			cmdFilter[2].Name = "_cmdFilter_2";
			cmdFilter[2].TabIndex = 3;
			cmdFilter[2].Text = "C";
			cmdFilter[3].BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			cmdFilter[3].Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.75F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			cmdFilter[3].ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			cmdFilter[3].Name = "_cmdFilter_3";
			cmdFilter[3].TabIndex = 4;
			cmdFilter[3].Text = "D";
			cmdFilter[1].BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			cmdFilter[1].Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.75F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			cmdFilter[1].ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			cmdFilter[1].Name = "_cmdFilter_1";
			cmdFilter[1].TabIndex = 2;
			cmdFilter[1].Text = "B";
			cmdFilter[0].BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			cmdFilter[0].Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.75F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			cmdFilter[0].ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			cmdFilter[0].Name = "_cmdFilter_0";
			cmdFilter[0].TabIndex = 1;
			cmdFilter[0].Text = "A";
			namedStyle1 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color65636234690624383796", "DataAreaDefault");
			namedStyle1.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 10F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle1.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle1.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle1.Parent = "DataAreaDefault";
			namedStyle1.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle2 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Text426636234690624393561", "DataAreaDefault");
			namedStyle2.CellType = textCellType1;
			namedStyle2.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 10F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle2.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle2.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle2.Parent = "DataAreaDefault";
			namedStyle2.Renderer = textCellType1;
			namedStyle2.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle3 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static814636234690624403326");
			namedStyle3.CellType = textCellType2;
			namedStyle3.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle3.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle3.Renderer = textCellType2;
			namedStyle3.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle4 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color1855636234690624510741");
			namedStyle4.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle4.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 12F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle4.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle4.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle4.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle4.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle5 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1889636234690624530271");
			namedStyle5.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle5.CellType = textCellType3;
			namedStyle5.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 12F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle5.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle5.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle5.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle5.Renderer = textCellType3;
			namedStyle5.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle6 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1988636234690624598626");
			namedStyle6.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle6.CellType = textCellType4;
			namedStyle6.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle6.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle6.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle6.Renderer = textCellType4;
			namedStyle6.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle7 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3050636234690625184526");
			namedStyle7.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle7.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle7.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle7.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle7.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle7.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle8 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3106636234690625213821");
			namedStyle8.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle8.CellType = textCellType5;
			namedStyle8.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle8.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle8.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle8.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle8.Renderer = textCellType5;
			namedStyle8.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle9 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3144636234690625233351");
			namedStyle9.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle9.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle9.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle9.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle9.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle10 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3220636234690625252881");
			namedStyle10.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle10.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle10.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle10.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle11 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3254636234690625282176");
			namedStyle11.CellType = textCellType6;
			namedStyle11.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle11.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle11.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle11.Renderer = textCellType6;
			namedStyle11.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle12 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3318636234690625291941");
			namedStyle12.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle12.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle12.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle12.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle13 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3352636234690625331001");
			namedStyle13.CellType = textCellType7;
			namedStyle13.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle13.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle13.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle13.Renderer = textCellType7;
			namedStyle13.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle14 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3390636234690625340766");
			namedStyle14.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle14.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle14.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle14.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle14.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle14.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle15 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3446636234690625389591");
			namedStyle15.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle15.CellType = textCellType8;
			namedStyle15.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle15.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle15.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle15.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle15.Renderer = textCellType8;
			namedStyle15.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle16 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3509636234690625399356");
			namedStyle16.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle16.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle16.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle16.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle16.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle16.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle17 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3585636234690625448181");
			namedStyle17.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle17.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle17.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle17.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle17.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle18 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3680636234690625516536");
			namedStyle18.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle18.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle18.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle18.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle18.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle19 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx4066636234690625780191");
			namedStyle19.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle19.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle19.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle20 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx80636234690625848546");
			namedStyle20.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle20.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle20.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle21 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx787636234690626434446");
			namedStyle21.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle21.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle21.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle21.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle22 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx841636234690626522331");
			namedStyle22.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle22.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle22.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle23 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1000636234690626688336");
			namedStyle23.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle23.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle23.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle23.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle23.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle23.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle24 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1095636234690626766456");
			namedStyle24.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle24.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle24.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle24.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle24.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle25 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1189636234690626834811");
			namedStyle25.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle25.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle25.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle25.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle26 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1223636234690626893401");
			namedStyle26.CellType = textCellType9;
			namedStyle26.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle26.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle26.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle26.Renderer = textCellType9;
			namedStyle26.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle27 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1278636234690626981286");
			namedStyle27.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle27.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle27.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle27.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle28 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1312636234690627030111");
			namedStyle28.CellType = textCellType10;
			namedStyle28.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle28.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle28.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle28.Renderer = textCellType10;
			namedStyle28.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle29 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1367636234690627059406");
			namedStyle29.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle29.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle29.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle29.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle29.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle29.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle30 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1423636234690627166821");
			namedStyle30.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle30.CellType = textCellType11;
			namedStyle30.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle30.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle30.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle30.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle30.Renderer = textCellType11;
			namedStyle30.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle31 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1478636234690627215646");
			namedStyle31.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle31.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle31.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle31.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle31.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle31.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle32 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1534636234690627332826");
			namedStyle32.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle32.CellType = textCellType12;
			namedStyle32.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle32.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle32.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle32.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle32.Renderer = textCellType12;
			namedStyle32.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle33 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1589636234690627381651");
			namedStyle33.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle33.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle33.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle33.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle33.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle34 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1678636234690627528126");
			namedStyle34.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle34.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle34.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle34.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle34.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle35 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx2167636234690628153086");
			namedStyle35.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle35.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle35.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle36 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx2278636234690628289796");
			namedStyle36.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle36.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle36.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle37 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3145636234690629627601");
			namedStyle37.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle37.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle37.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle37.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle38 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3179636234690629754546");
			namedStyle38.CellType = textCellType13;
			namedStyle38.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle38.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle38.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle38.Renderer = textCellType13;
			namedStyle38.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle39 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3241636234690629813136");
			namedStyle39.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle39.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle39.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle40 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3337636234690629988906");
			namedStyle40.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle40.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle40.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle40.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle40.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle40.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle41 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3393636234690630135381");
			namedStyle41.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle41.CellType = textCellType14;
			namedStyle41.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle41.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle41.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle41.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle41.Renderer = textCellType14;
			namedStyle41.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle42 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3484636234690630193971");
			namedStyle42.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle42.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle42.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle42.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle42.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle42.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle43 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3540636234690630379506");
			namedStyle43.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle43.CellType = textCellType15;
			namedStyle43.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle43.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle43.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle43.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle43.Renderer = textCellType15;
			namedStyle43.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle44 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3578636234690630438096");
			namedStyle44.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle44.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle44.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle44.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle44.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle45 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3654636234690630604101");
			namedStyle45.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle45.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle45.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle45.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle46 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3688636234690630721281");
			namedStyle46.CellType = textCellType16;
			namedStyle46.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle46.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle46.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle46.Renderer = textCellType16;
			namedStyle46.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle47 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3782636234690630926346");
			namedStyle47.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle47.CellType = textCellType17;
			namedStyle47.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle47.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle47.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle47.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle47.Renderer = textCellType17;
			namedStyle47.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle48 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static4042636234690631473186");
			namedStyle48.CellType = textCellType18;
			namedStyle48.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle48.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle48.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle48.Renderer = textCellType18;
			namedStyle48.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle49 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3726636234690630760341");
			namedStyle49.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
			namedStyle49.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle49.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle49.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle49.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle49.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle50 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static112636234690631834491");
			namedStyle50.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
			namedStyle50.CellType = textCellType19;
			namedStyle50.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle50.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle50.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle50.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle50.Renderer = textCellType19;
			namedStyle50.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle51 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx150636234690631883316");
			namedStyle51.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
			namedStyle51.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle51.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle51.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle51.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle52 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx244636234690632166501");
			namedStyle52.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(185)))), ((int)(((byte)(170)))));
			namedStyle52.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle52.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle52.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle52.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle52.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle53 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static300636234690632332506");
			namedStyle53.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(185)))), ((int)(((byte)(170)))));
			namedStyle53.CellType = textCellType20;
			namedStyle53.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle53.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle53.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle53.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle53.Renderer = textCellType20;
			namedStyle53.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle54 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx338636234690632371566");
			namedStyle54.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(185)))), ((int)(((byte)(170)))));
			namedStyle54.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle54.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle54.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle54.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle55 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx432636234690632537571");
			namedStyle55.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle55.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle55.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle56 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1240636234690634383156");
			namedStyle56.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(185)))), ((int)(((byte)(170)))));
			namedStyle56.CellType = textCellType21;
			namedStyle56.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle56.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle56.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle56.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle56.Renderer = textCellType21;
			namedStyle56.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle57 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1406636234690634685871");
			namedStyle57.CellType = textCellType22;
			namedStyle57.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle57.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle57.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle57.Renderer = textCellType22;
			namedStyle57.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle58 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3230636234690735255606");
			namedStyle58.CellType = textCellType23;
			namedStyle58.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle58.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle58.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle58.Renderer = textCellType23;
			namedStyle58.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle59 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Font2520636234690800397921");
			namedStyle59.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle59.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle59.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle59.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle60 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2538636234690800456511");
			namedStyle60.CellType = textCellType24;
			namedStyle60.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle60.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle60.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle60.Renderer = textCellType24;
			namedStyle60.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle61 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2588636234690800622516");
			namedStyle61.CellType = textCellType25;
			namedStyle61.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle61.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle61.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle61.Renderer = textCellType25;
			namedStyle61.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle62 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color1948636234690624549801");
			namedStyle62.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle62.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle62.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle62.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle62.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle62.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle63 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2644636234690800817816");
			namedStyle63.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle63.CellType = textCellType26;
			namedStyle63.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle63.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle63.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle63.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle63.Renderer = textCellType26;
			namedStyle63.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle64 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color2666636234690800866641");
			namedStyle64.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle64.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle64.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle64.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle64.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle65 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2790636234690801267006");
			namedStyle65.CellType = textCellType27;
			namedStyle65.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle65.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle65.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle65.Renderer = textCellType27;
			namedStyle65.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle66 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color2846636234690801433011");
			namedStyle66.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
			namedStyle66.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle66.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle66.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle66.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle66.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle67 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2880636234690801540426");
			namedStyle67.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
			namedStyle67.CellType = textCellType28;
			namedStyle67.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle67.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle67.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle67.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle67.Renderer = textCellType28;
			namedStyle67.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle68 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color2902636234690801599016");
			namedStyle68.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
			namedStyle68.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle68.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle68.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle68.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle69 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color2958636234690801804081");
			namedStyle69.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(185)))), ((int)(((byte)(170)))));
			namedStyle69.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle69.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle69.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle69.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle69.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle70 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2992636234690801931026");
			namedStyle70.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(185)))), ((int)(((byte)(170)))));
			namedStyle70.CellType = textCellType29;
			namedStyle70.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle70.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle70.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle70.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle70.Renderer = textCellType29;
			namedStyle70.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle71 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color3014636234690801979851");
			namedStyle71.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(185)))), ((int)(((byte)(170)))));
			namedStyle71.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle71.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle71.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle71.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle72 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3584636234690803815671");
			namedStyle72.CellType = textCellType30;
			namedStyle72.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle72.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle72.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle72.Renderer = textCellType30;
			namedStyle72.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			this.Name = "PTSProject.frmDailyStaffing";
			IsMdiChild = true;
			cboYear.Items.Add("1998");
			cboYear.Items.Add("1999");
			cboYear.Items.Add("2000");
			cboYear.Items.Add("2001");
			cboYear.Items.Add("2002");
			cboYear.Items.Add("2003");
			cboYear.Items.Add("2004");
			cboYear.Items.Add("2005");
			cboYear.Items.Add("2006");
			cboYear.Items.Add("2007");
			cboYear.Items.Add("2008");
			cboMonth.Items.Add("January");
			cboMonth.Items.Add("February");
			cboMonth.Items.Add("March");
			cboMonth.Items.Add("April");
			cboMonth.Items.Add("May");
			cboMonth.Items.Add("June");
			cboMonth.Items.Add("July");
			cboMonth.Items.Add("August");
			cboMonth.Items.Add("September");
			cboMonth.Items.Add("October");
			cboMonth.Items.Add("November");
			cboMonth.Items.Add("December");
			this.sprDaily.NamedStyles.Add(namedStyle1);
			this.sprDaily.NamedStyles.Add(namedStyle2);
			this.sprDaily.NamedStyles.Add(namedStyle3);
			this.sprDaily.NamedStyles.Add(namedStyle4);
			this.sprDaily.NamedStyles.Add(namedStyle5);
			this.sprDaily.NamedStyles.Add(namedStyle6);
			this.sprDaily.NamedStyles.Add(namedStyle7);
			this.sprDaily.NamedStyles.Add(namedStyle8);
			this.sprDaily.NamedStyles.Add(namedStyle9);
			this.sprDaily.NamedStyles.Add(namedStyle10);
			this.sprDaily.NamedStyles.Add(namedStyle11);
			this.sprDaily.NamedStyles.Add(namedStyle12);
			this.sprDaily.NamedStyles.Add(namedStyle13);
			this.sprDaily.NamedStyles.Add(namedStyle14);
			this.sprDaily.NamedStyles.Add(namedStyle15);
			this.sprDaily.NamedStyles.Add(namedStyle16);
			this.sprDaily.NamedStyles.Add(namedStyle17);
			this.sprDaily.NamedStyles.Add(namedStyle18);
			this.sprDaily.NamedStyles.Add(namedStyle19);
			this.sprDaily.NamedStyles.Add(namedStyle20);
			this.sprDaily.NamedStyles.Add(namedStyle21);
			this.sprDaily.NamedStyles.Add(namedStyle22);
			this.sprDaily.NamedStyles.Add(namedStyle23);
			this.sprDaily.NamedStyles.Add(namedStyle24);
			this.sprDaily.NamedStyles.Add(namedStyle25);
			this.sprDaily.NamedStyles.Add(namedStyle26);
			this.sprDaily.NamedStyles.Add(namedStyle27);
			this.sprDaily.NamedStyles.Add(namedStyle28);
			this.sprDaily.NamedStyles.Add(namedStyle29);
			this.sprDaily.NamedStyles.Add(namedStyle30);
			this.sprDaily.NamedStyles.Add(namedStyle31);
			this.sprDaily.NamedStyles.Add(namedStyle32);
			this.sprDaily.NamedStyles.Add(namedStyle33);
			this.sprDaily.NamedStyles.Add(namedStyle34);
			this.sprDaily.NamedStyles.Add(namedStyle35);
			this.sprDaily.NamedStyles.Add(namedStyle36);
			this.sprDaily.NamedStyles.Add(namedStyle37);
			this.sprDaily.NamedStyles.Add(namedStyle38);
			this.sprDaily.NamedStyles.Add(namedStyle39);
			this.sprDaily.NamedStyles.Add(namedStyle40);
			this.sprDaily.NamedStyles.Add(namedStyle41);
			this.sprDaily.NamedStyles.Add(namedStyle42);
			this.sprDaily.NamedStyles.Add(namedStyle43);
			this.sprDaily.NamedStyles.Add(namedStyle44);
			this.sprDaily.NamedStyles.Add(namedStyle45);
			this.sprDaily.NamedStyles.Add(namedStyle46);
			this.sprDaily.NamedStyles.Add(namedStyle47);
			this.sprDaily.NamedStyles.Add(namedStyle48);
			this.sprDaily.NamedStyles.Add(namedStyle49);
			this.sprDaily.NamedStyles.Add(namedStyle50);
			this.sprDaily.NamedStyles.Add(namedStyle51);
			this.sprDaily.NamedStyles.Add(namedStyle52);
			this.sprDaily.NamedStyles.Add(namedStyle53);
			this.sprDaily.NamedStyles.Add(namedStyle54);
			this.sprDaily.NamedStyles.Add(namedStyle55);
			this.sprDaily.NamedStyles.Add(namedStyle56);
			this.sprDaily.NamedStyles.Add(namedStyle57);
			this.sprDaily.NamedStyles.Add(namedStyle58);
			this.sprDaily.NamedStyles.Add(namedStyle59);
			this.sprDaily.NamedStyles.Add(namedStyle60);
			this.sprDaily.NamedStyles.Add(namedStyle61);
			this.sprDaily.NamedStyles.Add(namedStyle62);
			this.sprDaily.NamedStyles.Add(namedStyle63);
			this.sprDaily.NamedStyles.Add(namedStyle64);
			this.sprDaily.NamedStyles.Add(namedStyle65);
			this.sprDaily.NamedStyles.Add(namedStyle66);
			this.sprDaily.NamedStyles.Add(namedStyle67);
			this.sprDaily.NamedStyles.Add(namedStyle68);
			this.sprDaily.NamedStyles.Add(namedStyle69);
			this.sprDaily.NamedStyles.Add(namedStyle70);
			this.sprDaily.NamedStyles.Add(namedStyle71);
			this.sprDaily.NamedStyles.Add(namedStyle72);
			this.sprDaily.Sheets.Add(this.sprDaily_Sheet1);
		}

		public virtual UpgradeHelpers.BasicViewModels.ComboBoxViewModel cboYear { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ComboBoxViewModel cboMonth { get; set; }

		public virtual FarPoint.ViewModels.FpSpreadViewModel sprDaily { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.LabelViewModel Label3 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.LabelViewModel Label2 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.LabelViewModel Label1 { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual FarPoint.ViewModels.SheetViewModel sprDaily_Sheet1 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdAnnualLeave { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdOvertime { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel _cmdFilter_4 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel _cmdFilter_2 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel _cmdFilter_3 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel _cmdFilter_1 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel _cmdFilter_0 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdPrint { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdClose { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Int32 ThisMonth { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Int32 ThisYear { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.String CurrFilter { get; set; }

		public virtual System.Collections.Generic.IList<UpgradeHelpers.BasicViewModels.ButtonViewModel> cmdFilter { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Boolean IsDisposed { get; set; }

		public virtual bool IsMdiChild { get; set; }

	}

}