using UpgradeHelpers.Extensions;
using UpgradeHelpers.BasicViewModels.Extensions;
using UpgradeHelpers.Events;

namespace PTSProject.ViewModels
{

	[UpgradeHelpers.Helpers.Logic(Type = typeof(PTSProject.frmOvertime))]
	public class frmOvertimeViewModel
		: UpgradeHelpers.Helpers.FormBaseViewModel
	{

		public override void Build(UpgradeHelpers.Interfaces.IIocContainer ctx)
		{
			base.Build(ctx);
			var textCellType24 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle58;
			FarPoint.ViewModels.NamedStyle namedStyle57;
			var textCellType23 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle56;
			FarPoint.ViewModels.NamedStyle namedStyle55;
			var textCellType22 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle54;
			FarPoint.ViewModels.NamedStyle namedStyle53;
			var textCellType21 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle52;
			FarPoint.ViewModels.NamedStyle namedStyle51;
			var textCellType20 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle50;
			FarPoint.ViewModels.NamedStyle namedStyle49;
			var textCellType19 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle48;
			var textCellType18 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle47;
			FarPoint.ViewModels.NamedStyle namedStyle46;
			var textCellType17 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle45;
			FarPoint.ViewModels.NamedStyle namedStyle44;
			FarPoint.ViewModels.NamedStyle namedStyle43;
			var textCellType16 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle42;
			FarPoint.ViewModels.NamedStyle namedStyle41;
			var textCellType15 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle40;
			var textCellType14 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle39;
			FarPoint.ViewModels.NamedStyle namedStyle38;
			FarPoint.ViewModels.NamedStyle namedStyle37;
			var textCellType13 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle36;
			FarPoint.ViewModels.NamedStyle namedStyle35;
			FarPoint.ViewModels.NamedStyle namedStyle34;
			FarPoint.ViewModels.NamedStyle namedStyle33;
			FarPoint.ViewModels.NamedStyle namedStyle32;
			FarPoint.ViewModels.NamedStyle namedStyle31;
			var textCellType12 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle30;
			FarPoint.ViewModels.NamedStyle namedStyle29;
			var textCellType11 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle28;
			FarPoint.ViewModels.NamedStyle namedStyle27;
			var textCellType10 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle26;
			FarPoint.ViewModels.NamedStyle namedStyle25;
			var textCellType9 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle24;
			FarPoint.ViewModels.NamedStyle namedStyle23;
			FarPoint.ViewModels.NamedStyle namedStyle22;
			FarPoint.ViewModels.NamedStyle namedStyle21;
			FarPoint.ViewModels.NamedStyle namedStyle20;
			FarPoint.ViewModels.NamedStyle namedStyle19;
			FarPoint.ViewModels.NamedStyle namedStyle18;
			FarPoint.ViewModels.NamedStyle namedStyle17;
			FarPoint.ViewModels.NamedStyle namedStyle16;
			var textCellType8 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle15;
			FarPoint.ViewModels.NamedStyle namedStyle14;
			var textCellType7 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle13;
			FarPoint.ViewModels.NamedStyle namedStyle12;
			var textCellType6 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle11;
			FarPoint.ViewModels.NamedStyle namedStyle10;
			FarPoint.ViewModels.NamedStyle namedStyle9;
			var textCellType5 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle8;
			FarPoint.ViewModels.NamedStyle namedStyle7;
			var textCellType4 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle6;
			var textCellType3 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle5;
			FarPoint.ViewModels.NamedStyle namedStyle4;
			var textCellType2 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle3;
			var textCellType1 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle2;
			FarPoint.ViewModels.NamedStyle namedStyle1;
			this.sprOT = ctx.Resolve<FarPoint.ViewModels.FpSpreadViewModel>();
			this.sprOT.TabIndex = 6;
			this.sprOT.TextTip = FarPoint.ViewModels.TextTipPolicy.Off;
			this._cboOption_2 = ctx.Resolve<UpgradeHelpers.BasicViewModels.RadioButtonViewModel>();
			this._cboOption_1 = ctx.Resolve<UpgradeHelpers.BasicViewModels.RadioButtonViewModel>();
			this._cboOption_0 = ctx.Resolve<UpgradeHelpers.BasicViewModels.RadioButtonViewModel>();
			this.cboMonth = ctx.Resolve<UpgradeHelpers.BasicViewModels.ComboBoxViewModel>();
			// 
			// cboMonth
			// 
			this.cboMonth.BackColor = UpgradeHelpers.Helpers.SystemColors.Window;
			this.cboMonth.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10.8F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cboMonth.ForeColor = UpgradeHelpers.Helpers.SystemColors.WindowText;
			this.cboMonth.Name = "cboMonth";
			this.cboMonth.TabIndex = 3;
			this.cboYear = ctx.Resolve<UpgradeHelpers.BasicViewModels.ComboBoxViewModel>();
			// 
			// cboYear
			// 
			this.cboYear.BackColor = UpgradeHelpers.Helpers.SystemColors.Window;
			this.cboYear.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10.8F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cboYear.ForeColor = UpgradeHelpers.Helpers.SystemColors.WindowText;
			this.cboYear.Name = "cboYear";
			this.cboYear.TabIndex = 2;
			this.Label1 = ctx.Resolve<UpgradeHelpers.BasicViewModels.LabelViewModel>();
			// 
			// Label1
			// 
			this.Label1.BackColor = UpgradeHelpers.Helpers.Color.Transparent;
			this.Label1.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 12F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.Label1.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
			this.Label1.Name = "Label1";
			this.Label1.TabIndex = 5;
			this.Label1.Text = "Report Month";
			this.Label3 = ctx.Resolve<UpgradeHelpers.BasicViewModels.LabelViewModel>();
			// 
			// Label3
			// 
			this.Label3.BackColor = UpgradeHelpers.Helpers.Color.Transparent;
			this.Label3.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 12F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.Label3.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
			this.Label3.Name = "Label3";
			this.Label3.TabIndex = 4;
			this.Label3.Text = "Report Year";
			this.sprOT_Sheet1 = ctx.Resolve<FarPoint.ViewModels.SheetViewModel>();
			this.sprOT_Sheet1.SheetName = "Sheet1";
			this.sprOT_Sheet1.Cells.Get(0, 0).Value = "Tacoma Fire Department";
			this.sprOT_Sheet1.Cells.Get(1, 0).Value = "Unplanned Overtime Detail Report";
			this.sprOT_Sheet1.Cells.Get(2, 2).Value = "Officer";
			this.sprOT_Sheet1.Cells.Get(2, 4).Value = "Firefighter";
			this.sprOT_Sheet1.Cells.Get(2, 6).Value = "Paramedic";
			this.sprOT_Sheet1.Cells.Get(2, 8).Value = "Fireboat Officer";
			this.sprOT_Sheet1.Cells.Get(2, 10).Value = "Pilot";
			this.sprOT_Sheet1.Cells.Get(2, 12).Value = "BC";
			this.sprOT_Sheet1.Cells.Get(2, 14).Value = "BC Aide";
			this.sprOT_Sheet1.Cells.Get(2, 16).Value = "FCC";
			this.sprOT_Sheet1.Cells.Get(2, 18).Value = "Total (not FCC)";
			this.sprOT_Sheet1.Cells.Get(3, 0).Value = "Date";
			this.sprOT_Sheet1.Cells.Get(3, 1).Value = "Shf";
			this.sprOT_Sheet1.Cells.Get(3, 2).Value = "AM";
			this.sprOT_Sheet1.Cells.Get(3, 3).Value = "PM";
			this.sprOT_Sheet1.Cells.Get(3, 4).Value = "AM";
			this.sprOT_Sheet1.Cells.Get(3, 5).Value = "PM";
			this.sprOT_Sheet1.Cells.Get(3, 6).Value = "AM";
			this.sprOT_Sheet1.Cells.Get(3, 7).Value = "PM";
			this.sprOT_Sheet1.Cells.Get(3, 8).Value = "AM";
			this.sprOT_Sheet1.Cells.Get(3, 9).Value = "PM";
			this.sprOT_Sheet1.Cells.Get(3, 10).Value = "AM";
			this.sprOT_Sheet1.Cells.Get(3, 11).Value = "PM";
			this.sprOT_Sheet1.Cells.Get(3, 12).Value = "AM";
			this.sprOT_Sheet1.Cells.Get(3, 13).Value = "PM";
			this.sprOT_Sheet1.Cells.Get(3, 14).Value = "AM";
			this.sprOT_Sheet1.Cells.Get(3, 15).Value = "PM";
			this.sprOT_Sheet1.Cells.Get(3, 16).Value = "AM";
			this.sprOT_Sheet1.Cells.Get(3, 17).Value = "PM";
			this.sprOT_Sheet1.Cells.Get(3, 18).Value = "AM";
			this.sprOT_Sheet1.Cells.Get(3, 19).Value = "PM";
			this.sprOT_Sheet1.ColumnHeader.Rows.Get(0).Height = 0F;
			this.sprOT_Sheet1.Columns.Get(1).StyleName = "Static914636234748195020726";
			this.sprOT_Sheet1.Columns.Get(1).Width = 26F;
			this.sprOT_Sheet1.Columns.Get(2).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(3).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(4).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(5).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(6).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(7).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(8).Width = 38F;
			this.sprOT_Sheet1.Columns.Get(9).Width = 38F;
			this.sprOT_Sheet1.Columns.Get(10).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(11).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(12).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(13).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(14).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(15).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(16).Width = 38F;
			this.sprOT_Sheet1.Columns.Get(17).Width = 34F;
			this.sprOT_Sheet1.Columns.Get(18).Width = 35F;
			this.sprOT_Sheet1.Columns.Get(19).Width = 35F;
			this.sprOT_Sheet1.RowHeader.Columns.Get(0).Width = 0F;
			this.sprOT_Sheet1.Rows.Get(4).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(5).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(6).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(7).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(8).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(9).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(10).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(11).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(12).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(13).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(14).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(15).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(16).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(17).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(18).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(19).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(20).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(21).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(22).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(23).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(24).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(25).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(26).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(27).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(28).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(29).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(30).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(31).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(32).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(33).Height = 13F;
			this.sprOT_Sheet1.Rows.Get(34).Height = 13F;
			this.cmdClose = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdClose
			// 
			this.cmdClose.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdClose.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.6F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdClose.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdClose.Name = "cmdClose";
			this.cmdClose.TabIndex = 1;
			this.cmdClose.Text = "&Close";
			this.cmdPrint = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdPrint
			// 
			this.cmdPrint.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdPrint.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.6F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdPrint.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdPrint.Name = "cmdPrint";
			this.cmdPrint.TabIndex = 0;
			this.cmdPrint.Text = "&Print";
			this.Text = "Overtime Detail Report";
			this.OTMonth = 0;
			this.OTYear = 0;
			cboOption = ctx.Resolve<System.Collections.Generic.IList<UpgradeHelpers.BasicViewModels.RadioButtonViewModel>>(3);
			cboOption[2] = _cboOption_2;
			cboOption[1] = _cboOption_1;
			cboOption[0] = _cboOption_0;
			cboOption[2].BackColor = UpgradeHelpers.Helpers.Color.Teal;
			cboOption[2].Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7.8F, UpgradeHelpers.Helpers.FontStyle.Bold, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			cboOption[2].ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
			cboOption[2].Name = "_cboOption_2";
			cboOption[2].TabIndex = 10;
			cboOption[2].Text = "EDO Only";
			cboOption[1].BackColor = UpgradeHelpers.Helpers.Color.Teal;
			cboOption[1].Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7.8F, UpgradeHelpers.Helpers.FontStyle.Bold, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			cboOption[1].ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
			cboOption[1].Name = "_cboOption_1";
			cboOption[1].TabIndex = 9;
			cboOption[1].Text = "Planned OT";
			cboOption[0].BackColor = UpgradeHelpers.Helpers.Color.Teal;
			cboOption[0].Checked = true;
			cboOption[0].Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7.8F, UpgradeHelpers.Helpers.FontStyle.Bold, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			cboOption[0].ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
			cboOption[0].Name = "_cboOption_0";
			cboOption[0].TabIndex = 8;
			cboOption[0].Text = "Unplanned OT";
			namedStyle1 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color65636234748195001196", "DataAreaDefault");
			namedStyle1.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 10F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle1.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle1.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle1.Parent = "DataAreaDefault";
			namedStyle1.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle2 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Text526636234748195010961", "DataAreaDefault");
			namedStyle2.CellType = textCellType1;
			namedStyle2.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 10F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle2.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle2.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle2.Parent = "DataAreaDefault";
			namedStyle2.Renderer = textCellType1;
			namedStyle2.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle3 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static914636234748195020726");
			namedStyle3.CellType = textCellType2;
			namedStyle3.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle3.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle3.Renderer = textCellType2;
			namedStyle3.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle4 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color1732636234748195089081");
			namedStyle4.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle4.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 12F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle4.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle4.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle4.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle4.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle5 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1766636234748195098846");
			namedStyle5.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle5.CellType = textCellType3;
			namedStyle5.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 12F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle5.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle5.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle5.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle5.Renderer = textCellType3;
			namedStyle5.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle6 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1865636234748195216026");
			namedStyle6.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle6.CellType = textCellType4;
			namedStyle6.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle6.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle6.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle6.Renderer = textCellType4;
			namedStyle6.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle7 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3082636234748195694511");
			namedStyle7.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle7.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle7.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle7.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle7.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle7.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle8 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3138636234748195714041");
			namedStyle8.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle8.CellType = textCellType5;
			namedStyle8.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle8.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle8.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle8.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle8.Renderer = textCellType5;
			namedStyle8.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle9 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3176636234748195723806");
			namedStyle9.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle9.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle9.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle9.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle9.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle10 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3252636234748195772631");
			namedStyle10.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle10.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle10.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle10.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle11 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3286636234748195792161");
			namedStyle11.CellType = textCellType6;
			namedStyle11.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle11.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle11.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle11.Renderer = textCellType6;
			namedStyle11.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle12 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3346636234748195801926");
			namedStyle12.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle12.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle12.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle12.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle13 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3380636234748195840986");
			namedStyle13.CellType = textCellType7;
			namedStyle13.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle13.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle13.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle13.Renderer = textCellType7;
			namedStyle13.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle14 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3418636234748195850751");
			namedStyle14.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle14.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle14.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle14.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle14.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle14.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle15 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3474636234748195880046");
			namedStyle15.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle15.CellType = textCellType8;
			namedStyle15.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle15.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle15.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle15.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle15.Renderer = textCellType8;
			namedStyle15.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle16 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3538636234748195899576");
			namedStyle16.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle16.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle16.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle16.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle16.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle16.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle17 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3614636234748195938636");
			namedStyle17.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle17.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle17.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle17.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle17.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle18 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3732636234748195997226");
			namedStyle18.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle18.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle18.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle18.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle18.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle19 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3808636234748196026521");
			namedStyle19.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle19.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle19.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle20 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3933636234748196143701");
			namedStyle20.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle20.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle20.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle21 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx752636234748196729601");
			namedStyle21.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle21.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle21.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle21.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle21.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle21.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle22 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx847636234748196797956");
			namedStyle22.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle22.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle22.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle22.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle22.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle23 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx941636234748196856546");
			namedStyle23.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle23.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle23.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle23.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle24 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static975636234748196905371");
			namedStyle24.CellType = textCellType9;
			namedStyle24.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle24.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle24.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle24.Renderer = textCellType9;
			namedStyle24.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle25 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1030636234748196944431");
			namedStyle25.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle25.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle25.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle25.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle26 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1064636234748196993256");
			namedStyle26.CellType = textCellType10;
			namedStyle26.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle26.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle26.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle26.Renderer = textCellType10;
			namedStyle26.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle27 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1119636234748197012786");
			namedStyle27.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle27.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle27.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle27.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle27.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle27.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle28 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1175636234748197090906");
			namedStyle28.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle28.CellType = textCellType11;
			namedStyle28.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle28.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle28.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle28.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle28.Renderer = textCellType11;
			namedStyle28.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle29 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1230636234748197120201");
			namedStyle29.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle29.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle29.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle29.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle29.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle29.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle30 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1286636234748197198321");
			namedStyle30.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle30.CellType = textCellType12;
			namedStyle30.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle30.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle30.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle30.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle30.Renderer = textCellType12;
			namedStyle30.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle31 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1341636234748197247146");
			namedStyle31.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle31.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle31.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle31.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle31.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle32 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1452636234748197364326");
			namedStyle32.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle32.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle32.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle32.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle32.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle33 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1563636234748197471741");
			namedStyle33.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle33.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle33.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle34 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1674636234748197569391");
			namedStyle34.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle34.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle34.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle35 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx2748636234748198897431");
			namedStyle35.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle35.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle35.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle35.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle35.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle35.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle36 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2804636234748199014611");
			namedStyle36.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle36.CellType = textCellType13;
			namedStyle36.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle36.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle36.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle36.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle36.Renderer = textCellType13;
			namedStyle36.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle37 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx2842636234748199043906");
			namedStyle37.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle37.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle37.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle37.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle37.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle38 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx2918636234748199151321");
			namedStyle38.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle38.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle38.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle38.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle39 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2952636234748199248971");
			namedStyle39.CellType = textCellType14;
			namedStyle39.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle39.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle39.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle39.Renderer = textCellType14;
			namedStyle39.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle40 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3046636234748199414976");
			namedStyle40.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle40.CellType = textCellType15;
			namedStyle40.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle40.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle40.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle40.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle40.Renderer = textCellType15;
			namedStyle40.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle41 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx2990636234748199288031");
			namedStyle41.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(185)))), ((int)(((byte)(170)))));
			namedStyle41.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle41.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle41.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle41.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle41.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle42 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static376636234748201924581");
			namedStyle42.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(185)))), ((int)(((byte)(170)))));
			namedStyle42.CellType = textCellType16;
			namedStyle42.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle42.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle42.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle42.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle42.Renderer = textCellType16;
			namedStyle42.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle43 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx414636234748201953876");
			namedStyle43.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(185)))), ((int)(((byte)(170)))));
			namedStyle43.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle43.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle43.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle43.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle44 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx537636234748202139411");
			namedStyle44.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle44.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle44.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle45 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3380636234748273882866");
			namedStyle45.CellType = textCellType17;
			namedStyle45.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle45.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle45.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle45.Renderer = textCellType17;
			namedStyle45.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle46 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Font421636234748313860776");
			namedStyle46.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle46.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle46.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle46.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle47 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static439636234748313909601");
			namedStyle47.CellType = textCellType18;
			namedStyle47.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle47.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle47.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle47.Renderer = textCellType18;
			namedStyle47.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle48 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static489636234748314036546");
			namedStyle48.CellType = textCellType19;
			namedStyle48.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle48.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle48.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle48.Renderer = textCellType19;
			namedStyle48.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle49 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color1825636234748195186731");
			namedStyle49.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle49.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle49.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle49.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle49.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle49.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle50 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static545636234748314153726");
			namedStyle50.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle50.CellType = textCellType20;
			namedStyle50.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 7F);
			namedStyle50.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle50.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle50.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle50.Renderer = textCellType20;
			namedStyle50.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle51 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Font2471636234748318919046");
			namedStyle51.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle51.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle51.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle51.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle52 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2489636234748318967871");
			namedStyle52.CellType = textCellType21;
			namedStyle52.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle52.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle52.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle52.Renderer = textCellType21;
			namedStyle52.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle53 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Font2505636234748319006931");
			namedStyle53.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle53.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle53.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle53.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle54 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2539636234748319094816");
			namedStyle54.CellType = textCellType22;
			namedStyle54.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle54.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle54.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle54.Renderer = textCellType22;
			namedStyle54.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle55 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color567636234748314231846");
			namedStyle55.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle55.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle55.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle55.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle55.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle55.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle56 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2595636234748319241291");
			namedStyle56.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle56.CellType = textCellType23;
			namedStyle56.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle56.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle56.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle56.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle56.Renderer = textCellType23;
			namedStyle56.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle57 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color2617636234748319280351");
			namedStyle57.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle57.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle57.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle57.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle57.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle58 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1435636234748367158146");
			namedStyle58.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle58.CellType = textCellType24;
			namedStyle58.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle58.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle58.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle58.Renderer = textCellType24;
			namedStyle58.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			this.Name = "PTSProject.frmOvertime";
			IsMdiChild = true;
            cboMonth.Items.Add("January");
            cboMonth.SetItemData(cboMonth.GetNewIndex(), 1);
            cboMonth.Items.Add("February");
            cboMonth.SetItemData(cboMonth.GetNewIndex(), 2);
            cboMonth.Items.Add("March");
            cboMonth.SetItemData(cboMonth.GetNewIndex(), 3);
            cboMonth.Items.Add("April");
            cboMonth.SetItemData(cboMonth.GetNewIndex(), 4);
            cboMonth.Items.Add("May");
            cboMonth.SetItemData(cboMonth.GetNewIndex(), 5);
            cboMonth.Items.Add("June");
            cboMonth.SetItemData(cboMonth.GetNewIndex(), 6);
            cboMonth.Items.Add("July");
            cboMonth.SetItemData(cboMonth.GetNewIndex(), 7);
            cboMonth.Items.Add("August");
            cboMonth.SetItemData(cboMonth.GetNewIndex(), 8);
            cboMonth.Items.Add("September");
            cboMonth.SetItemData(cboMonth.GetNewIndex(), 9);
            cboMonth.Items.Add("October");
            cboMonth.SetItemData(cboMonth.GetNewIndex(), 10);
            cboMonth.Items.Add("November");
            cboMonth.SetItemData(cboMonth.GetNewIndex(), 11);
            cboMonth.Items.Add("December");
            cboMonth.SetItemData(cboMonth.GetNewIndex(), 12);
            cboYear.Items.Add("1998");
			cboYear.Items.Add("1999");
			cboYear.Items.Add("2000");
			cboYear.Items.Add("2001");
			cboYear.Items.Add("2002");
			cboYear.Items.Add("2003");
			cboYear.Items.Add("2004");
			cboYear.Items.Add("2005");
			this.sprOT.NamedStyles.Add(namedStyle1);
			this.sprOT.NamedStyles.Add(namedStyle2);
			this.sprOT.NamedStyles.Add(namedStyle3);
			this.sprOT.NamedStyles.Add(namedStyle4);
			this.sprOT.NamedStyles.Add(namedStyle5);
			this.sprOT.NamedStyles.Add(namedStyle6);
			this.sprOT.NamedStyles.Add(namedStyle7);
			this.sprOT.NamedStyles.Add(namedStyle8);
			this.sprOT.NamedStyles.Add(namedStyle9);
			this.sprOT.NamedStyles.Add(namedStyle10);
			this.sprOT.NamedStyles.Add(namedStyle11);
			this.sprOT.NamedStyles.Add(namedStyle12);
			this.sprOT.NamedStyles.Add(namedStyle13);
			this.sprOT.NamedStyles.Add(namedStyle14);
			this.sprOT.NamedStyles.Add(namedStyle15);
			this.sprOT.NamedStyles.Add(namedStyle16);
			this.sprOT.NamedStyles.Add(namedStyle17);
			this.sprOT.NamedStyles.Add(namedStyle18);
			this.sprOT.NamedStyles.Add(namedStyle19);
			this.sprOT.NamedStyles.Add(namedStyle20);
			this.sprOT.NamedStyles.Add(namedStyle21);
			this.sprOT.NamedStyles.Add(namedStyle22);
			this.sprOT.NamedStyles.Add(namedStyle23);
			this.sprOT.NamedStyles.Add(namedStyle24);
			this.sprOT.NamedStyles.Add(namedStyle25);
			this.sprOT.NamedStyles.Add(namedStyle26);
			this.sprOT.NamedStyles.Add(namedStyle27);
			this.sprOT.NamedStyles.Add(namedStyle28);
			this.sprOT.NamedStyles.Add(namedStyle29);
			this.sprOT.NamedStyles.Add(namedStyle30);
			this.sprOT.NamedStyles.Add(namedStyle31);
			this.sprOT.NamedStyles.Add(namedStyle32);
			this.sprOT.NamedStyles.Add(namedStyle33);
			this.sprOT.NamedStyles.Add(namedStyle34);
			this.sprOT.NamedStyles.Add(namedStyle35);
			this.sprOT.NamedStyles.Add(namedStyle36);
			this.sprOT.NamedStyles.Add(namedStyle37);
			this.sprOT.NamedStyles.Add(namedStyle38);
			this.sprOT.NamedStyles.Add(namedStyle39);
			this.sprOT.NamedStyles.Add(namedStyle40);
			this.sprOT.NamedStyles.Add(namedStyle41);
			this.sprOT.NamedStyles.Add(namedStyle42);
			this.sprOT.NamedStyles.Add(namedStyle43);
			this.sprOT.NamedStyles.Add(namedStyle44);
			this.sprOT.NamedStyles.Add(namedStyle45);
			this.sprOT.NamedStyles.Add(namedStyle46);
			this.sprOT.NamedStyles.Add(namedStyle47);
			this.sprOT.NamedStyles.Add(namedStyle48);
			this.sprOT.NamedStyles.Add(namedStyle49);
			this.sprOT.NamedStyles.Add(namedStyle50);
			this.sprOT.NamedStyles.Add(namedStyle51);
			this.sprOT.NamedStyles.Add(namedStyle52);
			this.sprOT.NamedStyles.Add(namedStyle53);
			this.sprOT.NamedStyles.Add(namedStyle54);
			this.sprOT.NamedStyles.Add(namedStyle55);
			this.sprOT.NamedStyles.Add(namedStyle56);
			this.sprOT.NamedStyles.Add(namedStyle57);
			this.sprOT.NamedStyles.Add(namedStyle58);
			this.sprOT.Sheets.Add(this.sprOT_Sheet1);
		}

		public virtual FarPoint.ViewModels.FpSpreadViewModel sprOT { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.RadioButtonViewModel _cboOption_2 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.RadioButtonViewModel _cboOption_1 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.RadioButtonViewModel _cboOption_0 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ComboBoxViewModel cboMonth { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ComboBoxViewModel cboYear { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.LabelViewModel Label1 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.LabelViewModel Label3 { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual FarPoint.ViewModels.SheetViewModel sprOT_Sheet1 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdClose { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdPrint { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Boolean isInitializingComponent { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Int32 OTMonth { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Int32 OTYear { get; set; }

		public virtual System.Collections.Generic.IList<UpgradeHelpers.BasicViewModels.RadioButtonViewModel> cboOption { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Boolean IsDisposed { get; set; }

		public virtual bool IsMdiChild { get; set; }

	}

}