using UpgradeHelpers.Extensions;
using UpgradeHelpers.BasicViewModels.Extensions;
using UpgradeHelpers.Events;

namespace PTSProject.ViewModels
{

	[UpgradeHelpers.Helpers.Logic(Type = typeof(PTSProject.frmPublicRoster))]
	public class frmPublicRosterViewModel
		: UpgradeHelpers.Helpers.FormBaseViewModel
	{

		public override void Build(UpgradeHelpers.Interfaces.IIocContainer ctx)
		{
			base.Build(ctx);
			var textCellType6 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle16;
			FarPoint.ViewModels.NamedStyle namedStyle15;
			FarPoint.ViewModels.NamedStyle namedStyle14;
			FarPoint.ViewModels.NamedStyle namedStyle13;
			var textCellType5 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle12;
			FarPoint.ViewModels.NamedStyle namedStyle11;
			var textCellType4 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle10;
			FarPoint.ViewModels.NamedStyle namedStyle9;
			FarPoint.ViewModels.NamedStyle namedStyle8;
			FarPoint.ViewModels.NamedStyle namedStyle7;
			var textCellType3 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle6;
			FarPoint.ViewModels.NamedStyle namedStyle5;
			var textCellType2 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle4;
			FarPoint.ViewModels.NamedStyle namedStyle3;
			var textCellType1 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle2;
			FarPoint.ViewModels.NamedStyle namedStyle1;
			this.sprRoster = ctx.Resolve<FarPoint.ViewModels.FpSpreadViewModel>();
			this.sprRoster.MaxRows = 700;
			this.sprRoster.TabIndex = 0;
			this.sprRoster.TextTip = FarPoint.ViewModels.TextTipPolicy.Off;
			this.cboName = ctx.Resolve<UpgradeHelpers.BasicViewModels.ComboBoxViewModel>();
			// 
			// cboName
			// 
			this.cboName.BackColor = UpgradeHelpers.Helpers.SystemColors.Window;
			this.cboName.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10.8F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cboName.ForeColor = UpgradeHelpers.Helpers.SystemColors.WindowText;
			this.cboName.Name = "cboName";
			this.cboName.TabIndex = 1;
			this.Label1 = ctx.Resolve<UpgradeHelpers.BasicViewModels.LabelViewModel>();
			// 
			// Label1
			// 
			this.Label1.BackColor = UpgradeHelpers.Helpers.Color.Transparent;
			this.Label1.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10.8F, UpgradeHelpers.Helpers.FontStyle.Bold, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.Label1.ForeColor = UpgradeHelpers.Helpers.Color.Maroon;
			this.Label1.Name = "Label1";
			this.Label1.TabIndex = 4;
			this.Label1.Text = "Find Employee";
			this.sprRoster_Sheet1 = ctx.Resolve<FarPoint.ViewModels.SheetViewModel>();
			this.sprRoster_Sheet1.SheetName = "Sheet1";
			this.sprRoster_Sheet1.Cells.Get(0, 0).Value = "Tacoma Fire Department";
			this.sprRoster_Sheet1.Cells.Get(0, 2).Value = "Page";
			this.sprRoster_Sheet1.Cells.Get(1, 0).Value = "Personnel Roster";
			this.sprRoster_Sheet1.Cells.Get(2, 0).Value = "Name";
			this.sprRoster_Sheet1.Cells.Get(2, 1).Value = "Address";
			this.sprRoster_Sheet1.Cells.Get(2, 2).Value = "Phone";
			this.sprRoster_Sheet1.ColumnHeader.Rows.Get(0).Height = 0F;
			this.sprRoster_Sheet1.Columns.Get(0).Width = 187F;
			this.sprRoster_Sheet1.Columns.Get(1).Width = 402F;
			this.sprRoster_Sheet1.Columns.Get(2).Width = 116F;
			this.sprRoster_Sheet1.Columns.Get(3).Resizable = false;
			this.sprRoster_Sheet1.Columns.Get(3).Visible = false;
			this.sprRoster_Sheet1.Columns.Get(3).Width = 0F;
			this.sprRoster_Sheet1.RowHeader.Columns.Get(0).Width = 0F;
			this.sprRoster_Sheet1.Rows.Get(3).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(4).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(5).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(6).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(7).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(8).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(9).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(10).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(11).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(12).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(13).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(14).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(15).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(16).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(17).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(18).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(19).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(20).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(21).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(22).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(23).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(24).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(25).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(26).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(27).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(28).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(29).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(30).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(31).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(32).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(33).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(34).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(35).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(36).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(37).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(38).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(39).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(40).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(41).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(42).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(43).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(44).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(45).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(46).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(47).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(48).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(49).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(50).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(51).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(52).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(53).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(54).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(55).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(56).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(57).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(58).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(59).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(60).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(61).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(62).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(63).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(64).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(65).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(66).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(67).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(68).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(69).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(70).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(71).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(72).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(73).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(74).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(75).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(76).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(77).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(78).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(79).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(80).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(81).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(82).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(83).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(84).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(85).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(86).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(87).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(88).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(89).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(90).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(91).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(92).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(93).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(94).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(95).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(96).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(97).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(98).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(99).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(100).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(101).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(102).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(103).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(104).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(105).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(106).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(107).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(108).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(109).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(110).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(111).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(112).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(113).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(114).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(115).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(116).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(117).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(118).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(119).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(120).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(121).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(122).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(123).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(124).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(125).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(126).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(127).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(128).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(129).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(130).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(131).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(132).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(133).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(134).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(135).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(136).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(137).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(138).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(139).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(140).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(141).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(142).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(143).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(144).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(145).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(146).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(147).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(148).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(149).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(150).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(151).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(152).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(153).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(154).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(155).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(156).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(157).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(158).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(159).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(160).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(161).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(162).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(163).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(164).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(165).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(166).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(167).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(168).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(169).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(170).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(171).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(172).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(173).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(174).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(175).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(176).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(177).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(178).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(179).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(180).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(181).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(182).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(183).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(184).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(185).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(186).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(187).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(188).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(189).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(190).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(191).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(192).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(193).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(194).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(195).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(196).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(197).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(198).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(199).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(200).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(201).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(202).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(203).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(204).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(205).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(206).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(207).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(208).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(209).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(210).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(211).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(212).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(213).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(214).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(215).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(216).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(217).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(218).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(219).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(220).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(221).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(222).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(223).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(224).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(225).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(226).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(227).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(228).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(229).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(230).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(231).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(232).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(233).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(234).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(235).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(236).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(237).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(238).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(239).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(240).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(241).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(242).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(243).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(244).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(245).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(246).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(247).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(248).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(249).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(250).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(251).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(252).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(253).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(254).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(255).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(256).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(257).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(258).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(259).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(260).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(261).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(262).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(263).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(264).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(265).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(266).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(267).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(268).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(269).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(270).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(271).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(272).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(273).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(274).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(275).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(276).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(277).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(278).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(279).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(280).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(281).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(282).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(283).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(284).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(285).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(286).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(287).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(288).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(289).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(290).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(291).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(292).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(293).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(294).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(295).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(296).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(297).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(298).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(299).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(300).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(301).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(302).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(303).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(304).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(305).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(306).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(307).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(308).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(309).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(310).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(311).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(312).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(313).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(314).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(315).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(316).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(317).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(318).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(319).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(320).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(321).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(322).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(323).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(324).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(325).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(326).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(327).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(328).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(329).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(330).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(331).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(332).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(333).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(334).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(335).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(336).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(337).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(338).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(339).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(340).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(341).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(342).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(343).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(344).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(345).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(346).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(347).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(348).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(349).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(350).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(351).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(352).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(353).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(354).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(355).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(356).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(357).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(358).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(359).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(360).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(361).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(362).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(363).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(364).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(365).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(366).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(367).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(368).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(369).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(370).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(371).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(372).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(373).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(374).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(375).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(376).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(377).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(378).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(379).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(380).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(381).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(382).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(383).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(384).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(385).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(386).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(387).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(388).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(389).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(390).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(391).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(392).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(393).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(394).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(395).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(396).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(397).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(398).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(399).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(400).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(401).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(402).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(403).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(404).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(405).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(406).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(407).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(408).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(409).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(410).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(411).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(412).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(413).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(414).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(415).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(416).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(417).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(418).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(419).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(420).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(421).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(422).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(423).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(424).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(425).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(426).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(427).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(428).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(429).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(430).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(431).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(432).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(433).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(434).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(435).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(436).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(437).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(438).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(439).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(440).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(441).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(442).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(443).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(444).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(445).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(446).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(447).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(448).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(449).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(450).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(451).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(452).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(453).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(454).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(455).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(456).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(457).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(458).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(459).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(460).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(461).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(462).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(463).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(464).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(465).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(466).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(467).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(468).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(469).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(470).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(471).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(472).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(473).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(474).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(475).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(476).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(477).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(478).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(479).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(480).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(481).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(482).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(483).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(484).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(485).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(486).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(487).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(488).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(489).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(490).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(491).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(492).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(493).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(494).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(495).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(496).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(497).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(498).Height = 19F;
			this.sprRoster_Sheet1.Rows.Get(499).Height = 19F;
			this.cmdPrint = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdPrint
			// 
			this.cmdPrint.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdPrint.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.6F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdPrint.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdPrint.Name = "cmdPrint";
			this.cmdPrint.TabIndex = 3;
			this.cmdPrint.Text = "&Print";
			this.cmdClose = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdClose
			// 
			this.cmdClose.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdClose.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.6F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdClose.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdClose.Name = "cmdClose";
			this.cmdClose.TabIndex = 2;
			this.cmdClose.Text = "&Close";
			this.Text = "Personnel Roster";
			this.CurrRow = 0;
			this.PageNo = 0;
			this.PageRow = 0;
			namedStyle1 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color65636234758694153426", "DataAreaDefault");
			namedStyle1.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial Narrow", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle1.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle1.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle1.Parent = "DataAreaDefault";
			namedStyle1.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle2 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Text517636234758694163191", "DataAreaDefault");
			namedStyle2.CellType = textCellType1;
			namedStyle2.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial Narrow", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle2.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle2.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle2.Parent = "DataAreaDefault";
			namedStyle2.Renderer = textCellType1;
			namedStyle2.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle3 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Font1065636234758694212016");
			namedStyle3.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 12F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle3.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle3.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle3.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle4 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1083636234758694221781");
			namedStyle4.CellType = textCellType2;
			namedStyle4.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 12F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle4.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle4.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle4.Renderer = textCellType2;
			namedStyle4.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle5 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Font1136636234758694241311");
			namedStyle5.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle5.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle5.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle5.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle6 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1154636234758694251076");
			namedStyle6.CellType = textCellType3;
			namedStyle6.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle6.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle6.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle6.Renderer = textCellType3;
			namedStyle6.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle7 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Font1299636234758694299901");
			namedStyle7.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial Narrow", 12F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle7.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle7.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle7.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle8 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Font1315636234758694309666");
			namedStyle8.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial Narrow", 10F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle8.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle8.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle8.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle9 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1364636234758694319431");
			namedStyle9.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10F);
			namedStyle9.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle9.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle9.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle10 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1398636234758694358491");
			namedStyle10.CellType = textCellType4;
			namedStyle10.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10F);
			namedStyle10.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle10.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle10.Renderer = textCellType4;
			namedStyle10.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle11 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1455636234758694378021");
			namedStyle11.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10F);
			namedStyle11.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle11.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle11.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle12 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1489636234758694407316");
			namedStyle12.CellType = textCellType5;
			namedStyle12.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10F);
			namedStyle12.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle12.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle12.Renderer = textCellType5;
			namedStyle12.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle13 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1549636234758694417081");
			namedStyle13.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle13.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle13.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle14 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1641636234758694475671");
			namedStyle14.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle14.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle14.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle15 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Font1657636234758694485436");
			namedStyle15.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10F);
			namedStyle15.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle15.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle15.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle16 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1704636234758694504966");
			namedStyle16.CellType = textCellType6;
			namedStyle16.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle16.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle16.Renderer = textCellType6;
			namedStyle16.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			this.Name = "PTSProject.frmPublicRoster";
			IsMdiChild = true;
			this.sprRoster.NamedStyles.Add(namedStyle1);
			this.sprRoster.NamedStyles.Add(namedStyle2);
			this.sprRoster.NamedStyles.Add(namedStyle3);
			this.sprRoster.NamedStyles.Add(namedStyle4);
			this.sprRoster.NamedStyles.Add(namedStyle5);
			this.sprRoster.NamedStyles.Add(namedStyle6);
			this.sprRoster.NamedStyles.Add(namedStyle7);
			this.sprRoster.NamedStyles.Add(namedStyle8);
			this.sprRoster.NamedStyles.Add(namedStyle9);
			this.sprRoster.NamedStyles.Add(namedStyle10);
			this.sprRoster.NamedStyles.Add(namedStyle11);
			this.sprRoster.NamedStyles.Add(namedStyle12);
			this.sprRoster.NamedStyles.Add(namedStyle13);
			this.sprRoster.NamedStyles.Add(namedStyle14);
			this.sprRoster.NamedStyles.Add(namedStyle15);
			this.sprRoster.NamedStyles.Add(namedStyle16);
			this.sprRoster.Sheets.Add(this.sprRoster_Sheet1);
		}

		public virtual FarPoint.ViewModels.FpSpreadViewModel sprRoster { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ComboBoxViewModel cboName { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.LabelViewModel Label1 { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual FarPoint.ViewModels.SheetViewModel sprRoster_Sheet1 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdPrint { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdClose { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Int32 CurrRow { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Int32 PageNo { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Int32 PageRow { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Boolean IsDisposed { get; set; }

		public virtual bool IsMdiChild { get; set; }

	}

}