using UpgradeHelpers.Extensions;
using UpgradeHelpers.BasicViewModels.Extensions;
using UpgradeHelpers.Events;

namespace PTSProject.ViewModels
{

	[UpgradeHelpers.Helpers.Logic(Type = typeof(PTSProject.frmTimeCard1))]
	public class frmTimeCard1ViewModel
		: UpgradeHelpers.Helpers.FormBaseViewModel
	{

		public override void Build(UpgradeHelpers.Interfaces.IIocContainer ctx)
		{
			base.Build(ctx);
			var textCellType37 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle74;
			FarPoint.ViewModels.NamedStyle namedStyle73;
			var textCellType36 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle72;
			FarPoint.ViewModels.NamedStyle namedStyle71;
			var textCellType35 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle70;
			FarPoint.ViewModels.NamedStyle namedStyle69;
			var textCellType34 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle68;
			FarPoint.ViewModels.NamedStyle namedStyle67;
			FarPoint.ViewModels.NamedStyle namedStyle66;
			var textCellType33 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle65;
			FarPoint.ViewModels.NamedStyle namedStyle64;
			var textCellType32 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle63;
			FarPoint.ViewModels.NamedStyle namedStyle62;
			var textCellType31 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle61;
			FarPoint.ViewModels.NamedStyle namedStyle60;
			FarPoint.ViewModels.NamedStyle namedStyle59;
			FarPoint.ViewModels.NamedStyle namedStyle58;
			var textCellType30 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle57;
			FarPoint.ViewModels.NamedStyle namedStyle56;
			FarPoint.ViewModels.NamedStyle namedStyle55;
			FarPoint.ViewModels.NamedStyle namedStyle54;
			var textCellType29 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle53;
			FarPoint.ViewModels.NamedStyle namedStyle52;
			var textCellType28 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle51;
			FarPoint.ViewModels.NamedStyle namedStyle50;
			var textCellType27 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle49;
			var textCellType26 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle48;
			var textCellType25 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle47;
			FarPoint.ViewModels.NamedStyle namedStyle46;
			FarPoint.ViewModels.NamedStyle namedStyle45;
			FarPoint.ViewModels.NamedStyle namedStyle44;
			var textCellType24 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle43;
			FarPoint.ViewModels.NamedStyle namedStyle42;
			var textCellType23 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle41;
			FarPoint.ViewModels.NamedStyle namedStyle40;
			var textCellType22 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle39;
			FarPoint.ViewModels.NamedStyle namedStyle38;
			FarPoint.ViewModels.NamedStyle namedStyle37;
			FarPoint.ViewModels.NamedStyle namedStyle36;
			FarPoint.ViewModels.NamedStyle namedStyle35;
			FarPoint.ViewModels.NamedStyle namedStyle34;
			FarPoint.ViewModels.NamedStyle namedStyle33;
			var textCellType21 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle32;
			FarPoint.ViewModels.NamedStyle namedStyle31;
			var textCellType20 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle30;
			FarPoint.ViewModels.NamedStyle namedStyle29;
			FarPoint.ViewModels.NamedStyle namedStyle28;
			var textCellType19 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle27;
			FarPoint.ViewModels.NamedStyle namedStyle26;
			var textCellType18 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle25;
			FarPoint.ViewModels.NamedStyle namedStyle24;
			var textCellType17 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle23;
			var textCellType16 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle22;
			var textCellType15 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle21;
			var textCellType14 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle20;
			var textCellType13 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle19;
			var textCellType12 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle18;
			var textCellType11 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle17;
			var textCellType10 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle16;
			FarPoint.ViewModels.NamedStyle namedStyle15;
			var textCellType9 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle14;
			var textCellType8 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle13;
			FarPoint.ViewModels.NamedStyle namedStyle12;
			var textCellType7 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle11;
			var textCellType6 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle10;
			var textCellType5 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle9;
			var textCellType4 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle8;
			var textCellType3 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle7;
			FarPoint.ViewModels.NamedStyle namedStyle6;
			FarPoint.ViewModels.NamedStyle namedStyle5;
			var textCellType2 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle4;
			FarPoint.ViewModels.NamedStyle namedStyle3;
			var textCellType1 = ctx.Resolve<FarPoint.ViewModels.TextCellType>();
			FarPoint.ViewModels.NamedStyle namedStyle2;
			FarPoint.ViewModels.NamedStyle namedStyle1;
			this.sprBatt = ctx.Resolve<FarPoint.ViewModels.FpSpreadViewModel>();
			this.sprBatt.MaxRows = 499;
			this.sprBatt.TabIndex = 6;
			this.sprBatt.TextTip = FarPoint.ViewModels.TextTipPolicy.Off;
			this.calDate = ctx.Resolve<WNFRMS.Viewmodels.DateTimePickerViewModel>();
			this.calDate.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 10.8F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.calDate.MaxDate = new System.DateTime(2999, 12, 31, 0, 0, 0, 0);
			this.calDate.MinDate = new System.DateTime(1996, 1, 1, 0, 0, 0, 0);
			this.calDate.Name = "calDate";
			this.calDate.TabIndex = 0;
			this.Label1 = ctx.Resolve<UpgradeHelpers.BasicViewModels.LabelViewModel>();
			// 
			// Label1
			// 
			this.Label1.BackColor = UpgradeHelpers.Helpers.Color.Transparent;
			this.Label1.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 11.4F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.Label1.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
			this.Label1.Name = "Label1";
			this.Label1.TabIndex = 5;
			this.Label1.Text = "Select Report Date";
			this.sprBatt_Sheet1 = ctx.Resolve<FarPoint.ViewModels.SheetViewModel>();
			this.sprBatt_Sheet1.SheetName = "Sheet1";
			this.sprBatt_Sheet1.Cells.Get(0, 0).Value = "Tacoma Fire Department";
			this.sprBatt_Sheet1.Cells.Get(1, 0).Value = "Battalion 1 Time Card Worksheet";
			this.sprBatt_Sheet1.Cells.Get(1, 7).Value = "MM/DD/YY";
			this.sprBatt_Sheet1.Cells.Get(1, 12).Value = "Shift";
			this.sprBatt_Sheet1.Cells.Get(1, 13).Value = "A";
			this.sprBatt_Sheet1.Cells.Get(1, 18).Value = "Debit Grp";
			this.sprBatt_Sheet1.Cells.Get(1, 19).Value = "C11";
			this.sprBatt_Sheet1.Cells.Get(2, 0).Value = "BC01";
			this.sprBatt_Sheet1.Cells.Get(2, 6).Value = "E4";
			this.sprBatt_Sheet1.Cells.Get(2, 12).Value = "E9";
			this.sprBatt_Sheet1.Cells.Get(2, 18).Value = "E13";
			this.sprBatt_Sheet1.Cells.Get(2, 24).Value = "E14";
			this.sprBatt_Sheet1.Cells.Get(15, 0).Value = "E16";
			this.sprBatt_Sheet1.Cells.Get(15, 6).Value = "E17";
			this.sprBatt_Sheet1.Cells.Get(15, 12).Value = "L3";
			this.sprBatt_Sheet1.Cells.Get(15, 18).Value = "M1";
			this.sprBatt_Sheet1.Cells.Get(15, 24).Value = "M4";
			this.sprBatt_Sheet1.Cells.Get(26, 0).Value = "SAF03";
			this.sprBatt_Sheet1.Cells.Get(26, 18).Value = "FCC";
			this.sprBatt_Sheet1.Cells.Get(26, 24).Value = "Notes:";
			this.sprBatt_Sheet1.Cells.Get(37, 0).Value = "Rovers";
			this.sprBatt_Sheet1.Cells.Get(37, 6).Value = "Debit";
			this.sprBatt_Sheet1.Cells.Get(37, 12).Value = "Special Assignment";
			this.sprBatt_Sheet1.Cells.Get(42, 18).Value = "I ATTEST THAT THE PEOPLE, POSITIONS, KINDS OF TIME AND ";
			this.sprBatt_Sheet1.Cells.Get(43, 18).Value = "HOURS WORKED SHOWN ON THIS WORK SCHEDULE ";
			this.sprBatt_Sheet1.Cells.Get(44, 18).Value = "FOR______________  SHIFT______  BATTALION______";
			this.sprBatt_Sheet1.Cells.Get(45, 18).Value = "ARE CORRECT TO MY KNOWLEDGE.";
			this.sprBatt_Sheet1.Cells.Get(46, 18).Value = "SIGNED BY B.C.______________________________________";
			this.sprBatt_Sheet1.Cells.Get(47, 18).Value = "DATED";
			this.sprBatt_Sheet1.Cells.Get(48, 0).Value = "TFD Battalion 3 Time Card Worksheet";
			this.sprBatt_Sheet1.ColumnHeader.Rows.Get(0).Height = 0F;
			this.sprBatt_Sheet1.Columns.Get(0).Width = 71F;
			this.sprBatt_Sheet1.Columns.Get(1).Width = 46F;
			this.sprBatt_Sheet1.Columns.Get(2).Width = 12F;
			this.sprBatt_Sheet1.Columns.Get(3).StyleName = "Static925636234775704129171";
			this.sprBatt_Sheet1.Columns.Get(3).Width = 14F;
			this.sprBatt_Sheet1.Columns.Get(4).Width = 34F;
			this.sprBatt_Sheet1.Columns.Get(5).Width = 9F;
			this.sprBatt_Sheet1.Columns.Get(6).Width = 71F;
			this.sprBatt_Sheet1.Columns.Get(7).Width = 46F;
			this.sprBatt_Sheet1.Columns.Get(8).Width = 12F;
			this.sprBatt_Sheet1.Columns.Get(9).StyleName = "Static925636234775704129171";
			this.sprBatt_Sheet1.Columns.Get(9).Width = 12F;
			this.sprBatt_Sheet1.Columns.Get(10).Width = 39F;
			this.sprBatt_Sheet1.Columns.Get(11).Width = 10F;
			this.sprBatt_Sheet1.Columns.Get(12).Width = 71F;
			this.sprBatt_Sheet1.Columns.Get(13).Width = 46F;
			this.sprBatt_Sheet1.Columns.Get(14).Width = 12F;
			this.sprBatt_Sheet1.Columns.Get(15).StyleName = "Static925636234775704129171";
			this.sprBatt_Sheet1.Columns.Get(15).Width = 12F;
			this.sprBatt_Sheet1.Columns.Get(16).Width = 34F;
			this.sprBatt_Sheet1.Columns.Get(17).Width = 11F;
			this.sprBatt_Sheet1.Columns.Get(18).Width = 71F;
			this.sprBatt_Sheet1.Columns.Get(19).Width = 46F;
			this.sprBatt_Sheet1.Columns.Get(20).Width = 12F;
			this.sprBatt_Sheet1.Columns.Get(21).StyleName = "Static925636234775704129171";
			this.sprBatt_Sheet1.Columns.Get(21).Width = 12F;
			this.sprBatt_Sheet1.Columns.Get(22).Width = 38F;
			this.sprBatt_Sheet1.Columns.Get(23).Width = 10F;
			this.sprBatt_Sheet1.Columns.Get(24).Width = 70F;
			this.sprBatt_Sheet1.Columns.Get(25).Width = 46F;
			this.sprBatt_Sheet1.Columns.Get(26).Width = 12F;
			this.sprBatt_Sheet1.Columns.Get(27).StyleName = "Color866636234775704119406";
			this.sprBatt_Sheet1.Columns.Get(27).Width = 12F;
			this.sprBatt_Sheet1.Columns.Get(28).Width = 34F;
			this.sprBatt_Sheet1.Columns.Get(29).Width = 14F;
			this.sprBatt_Sheet1.RowHeader.Columns.Get(0).Width = 0F;
			this.sprBatt_Sheet1.Rows.Get(2).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(4).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(5).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(6).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(7).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(8).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(9).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(10).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(11).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(12).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(13).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(14).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(15).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(16).Height = 17F;
			this.sprBatt_Sheet1.Rows.Get(17).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(18).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(19).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(20).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(21).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(22).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(23).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(24).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(25).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(26).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(27).Height = 15F;
			this.sprBatt_Sheet1.Rows.Get(28).Height = 15F;
			this.sprBatt_Sheet1.Rows.Get(29).Height = 15F;
			this.sprBatt_Sheet1.Rows.Get(30).Height = 15F;
			this.sprBatt_Sheet1.Rows.Get(31).Height = 15F;
			this.sprBatt_Sheet1.Rows.Get(32).Height = 15F;
			this.sprBatt_Sheet1.Rows.Get(33).Height = 15F;
			this.sprBatt_Sheet1.Rows.Get(34).Height = 15F;
			this.sprBatt_Sheet1.Rows.Get(35).Height = 15F;
			this.sprBatt_Sheet1.Rows.Get(36).Height = 15F;
			this.sprBatt_Sheet1.Rows.Get(37).Height = 14F;
			this.sprBatt_Sheet1.Rows.Get(48).Height = 13F;
			this.cmdPrintAll = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdPrintAll
			// 
			this.cmdPrintAll.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdPrintAll.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.6F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdPrintAll.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdPrintAll.Name = "cmdPrintAll";
			this.cmdPrintAll.TabIndex = 7;
			this.cmdPrintAll.Text = "Print &All Daily Reports";
			this.cmdLeave = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdLeave
			// 
			this.cmdLeave.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdLeave.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.6F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdLeave.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdLeave.Name = "cmdLeave";
			this.cmdLeave.TabIndex = 3;
			this.cmdLeave.Text = "&Leave Report";
			this.cmdExcept = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdExcept
			// 
			this.cmdExcept.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdExcept.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.6F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdExcept.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdExcept.Name = "cmdExcept";
			this.cmdExcept.TabIndex = 2;
			this.cmdExcept.Text = "E&xception Report";
			this.cmdClose = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdClose
			// 
			this.cmdClose.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdClose.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.6F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdClose.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdClose.Name = "cmdClose";
			this.cmdClose.TabIndex = 4;
			this.cmdClose.Text = "&Close";
			this.cmdPrint = ctx.Resolve<UpgradeHelpers.BasicViewModels.ButtonViewModel>();
			// 
			// cmdPrint
			// 
			this.cmdPrint.BackColor = UpgradeHelpers.Helpers.SystemColors.Control;
			this.cmdPrint.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 9.6F, UpgradeHelpers.Helpers.FontStyle.Regular, UpgradeHelpers.Helpers.GraphicsUnit.Point, ((byte)(0)));
			this.cmdPrint.ForeColor = UpgradeHelpers.Helpers.SystemColors.ControlText;
			this.cmdPrint.Name = "cmdPrint";
			this.cmdPrint.TabIndex = 1;
			this.cmdPrint.Text = "&Print Worksheet";
			this.Text = "Battalion 1 Time Card Worksheet";
			this.FirstTime = 0;
			namedStyle1 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color65636234775704090111", "DataAreaDefault");
			namedStyle1.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 10F);
			namedStyle1.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle1.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle1.Parent = "DataAreaDefault";
			namedStyle1.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle2 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Text441636234775704099876", "DataAreaDefault");
			namedStyle2.CellType = textCellType1;
			namedStyle2.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 10F);
			namedStyle2.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle2.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle2.Parent = "DataAreaDefault";
			namedStyle2.Renderer = textCellType1;
			namedStyle2.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle3 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color866636234775704119406");
			namedStyle3.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle3.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle3.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle3.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle3.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle4 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static925636234775704129171");
			namedStyle4.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle4.CellType = textCellType2;
			namedStyle4.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle4.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle4.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle4.Renderer = textCellType2;
			namedStyle4.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle5 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Font960636234775704226821");
			namedStyle5.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 10F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle5.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle5.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle5.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle6 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color1011636234775704226821");
			namedStyle6.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle6.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle6.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle6.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle6.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle7 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1287636234775704402591");
			namedStyle7.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle7.CellType = textCellType3;
			namedStyle7.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle7.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle7.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle7.Renderer = textCellType3;
			namedStyle7.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle8 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1458636234775704490476");
			namedStyle8.CellType = textCellType4;
			namedStyle8.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle8.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle8.Renderer = textCellType4;
			namedStyle8.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle9 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1494636234775704519771");
			namedStyle9.CellType = textCellType5;
			namedStyle9.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Right;
			namedStyle9.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle9.Renderer = textCellType5;
			namedStyle9.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle10 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1554636234775704607656");
			namedStyle10.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle10.CellType = textCellType6;
			namedStyle10.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
			namedStyle10.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle10.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle10.Renderer = textCellType6;
			namedStyle10.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle11 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1688636234775704695541");
			namedStyle11.CellType = textCellType7;
			namedStyle11.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle11.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle11.Renderer = textCellType7;
			namedStyle11.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle12 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Font1722636234775704715071");
			namedStyle12.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle12.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle12.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle12.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle13 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1769636234775704754131");
			namedStyle13.CellType = textCellType8;
			namedStyle13.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle13.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle13.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle13.Renderer = textCellType8;
			namedStyle13.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle14 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1825636234775704871311");
			namedStyle14.CellType = textCellType9;
			namedStyle14.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle14.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle14.Renderer = textCellType9;
			namedStyle14.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle15 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Font3104636234775705964991");
			namedStyle15.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle15.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle15.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle15.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle16 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3189636234775706082171");
			namedStyle16.CellType = textCellType10;
			namedStyle16.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle16.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle16.Renderer = textCellType10;
			namedStyle16.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle17 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3245636234775706140761");
			namedStyle17.CellType = textCellType11;
			namedStyle17.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle17.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle17.Renderer = textCellType11;
			namedStyle17.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle18 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static318636234775707527391");
			namedStyle18.CellType = textCellType12;
			namedStyle18.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle18.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle18.Renderer = textCellType12;
			namedStyle18.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle19 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2180636234775715866701");
			namedStyle19.CellType = textCellType13;
			namedStyle19.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle19.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle19.Renderer = textCellType13;
			namedStyle19.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle20 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2236636234775715915526");
			namedStyle20.CellType = textCellType14;
			namedStyle20.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle20.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle20.Renderer = textCellType14;
			namedStyle20.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle21 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3761636234775717966176");
			namedStyle21.CellType = textCellType15;
			namedStyle21.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle21.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle21.Renderer = textCellType15;
			namedStyle21.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle22 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static280636234775739410116");
			namedStyle22.CellType = textCellType16;
			namedStyle22.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle22.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle22.Renderer = textCellType16;
			namedStyle22.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle23 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2015636234775742456796");
			namedStyle23.CellType = textCellType17;
			namedStyle23.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle23.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle23.Renderer = textCellType17;
			namedStyle23.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle24 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1807636234775704851781");
			namedStyle24.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle24.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle24.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle24.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle25 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3556636234775752797931");
			namedStyle25.CellType = textCellType18;
			namedStyle25.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle25.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle25.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle25.Renderer = textCellType18;
			namedStyle25.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle26 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1882636234775704890841");
			namedStyle26.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle26.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle26.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle26.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle27 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3649636234775752983466");
			namedStyle27.CellType = textCellType19;
			namedStyle27.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle27.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle27.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle27.Renderer = textCellType19;
			namedStyle27.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle28 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx2034636234775704988491");
			namedStyle28.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle28.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle28.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle28.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle29 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3939636234775753461951");
			namedStyle29.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255)))));
			namedStyle29.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle29.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle29.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle29.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle29.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle30 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3995636234775753598661");
			namedStyle30.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255)))));
			namedStyle30.CellType = textCellType20;
			namedStyle30.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle30.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle30.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle30.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle30.Renderer = textCellType20;
			namedStyle30.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle31 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3687636234775753012761");
			namedStyle31.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255)))));
			namedStyle31.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle31.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle31.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle31.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle31.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle32 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static18636234775753793961");
			namedStyle32.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255)))));
			namedStyle32.CellType = textCellType21;
			namedStyle32.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle32.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle32.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle32.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle32.Renderer = textCellType21;
			namedStyle32.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle33 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx56636234775753842786");
			namedStyle33.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255)))));
			namedStyle33.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle33.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle33.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle33.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle34 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx132636234775753999026");
			namedStyle34.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle34.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle34.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle35 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx320636234775754340801");
			namedStyle35.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255)))));
			namedStyle35.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle35.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle35.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle35.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle35.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle36 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx396636234775754477511");
			namedStyle36.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle36.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle36.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle37 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx755636234775755151296");
			namedStyle37.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle37.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle37.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle38 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Color833636234775755307536");
			namedStyle38.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle38.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle38.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle38.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle38.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle39 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static851636234775755346596");
			namedStyle39.BackColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle39.CellType = textCellType22;
			namedStyle39.ForeColor = UpgradeHelpers.Helpers.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			namedStyle39.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle39.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle39.Renderer = textCellType22;
			namedStyle39.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle40 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3171636234775706052876");
			namedStyle40.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle40.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle40.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle40.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle41 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1274636234775756108266");
			namedStyle41.CellType = textCellType23;
			namedStyle41.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle41.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle41.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle41.Renderer = textCellType23;
			namedStyle41.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle42 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3227636234775706121231");
			namedStyle42.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle42.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle42.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle42.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle43 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1346636234775756244976");
			namedStyle43.CellType = textCellType24;
			namedStyle43.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle43.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle43.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle43.Renderer = textCellType24;
			namedStyle43.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle44 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3433636234775706336061");
			namedStyle44.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle44.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle44.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle44.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle45 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx300636234775707498096");
			namedStyle45.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle45.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle45.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle45.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle46 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx410636234775707673866");
			namedStyle46.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle46.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle46.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle46.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle47 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static247636234775762533636");
			namedStyle47.CellType = textCellType25;
			namedStyle47.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle47.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle47.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle47.Renderer = textCellType25;
			namedStyle47.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle48 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static281636234775762621521");
			namedStyle48.CellType = textCellType26;
			namedStyle48.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle48.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle48.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle48.Renderer = textCellType26;
			namedStyle48.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle49 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1243636234775764574521");
			namedStyle49.CellType = textCellType27;
			namedStyle49.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle49.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle49.Renderer = textCellType27;
			namedStyle49.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle50 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1636636234775757182416");
			namedStyle50.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle50.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle50.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle50.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle51 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2376636234775766976711");
			namedStyle51.CellType = textCellType28;
			namedStyle51.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle51.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle51.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle51.Renderer = textCellType28;
			namedStyle51.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Bottom;
			namedStyle52 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1384636234775756332861");
			namedStyle52.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle52.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle52.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle52.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle53 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static2518636234775767152481");
			namedStyle53.CellType = textCellType29;
			namedStyle53.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle53.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle53.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle53.Renderer = textCellType29;
			namedStyle53.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle54 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx2556636234775767191541");
			namedStyle54.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle54.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle54.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle55 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1978636234775757846436");
			namedStyle55.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle55.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle55.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle55.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle56 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx2977636234775759916616");
			namedStyle56.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle56.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle56.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle56.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle57 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static3999636234775770150336");
			namedStyle57.CellType = textCellType30;
			namedStyle57.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle57.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle57.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle57.Renderer = textCellType30;
			namedStyle57.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle58 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx3095636234775760160741");
			namedStyle58.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle58.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle58.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle58.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle59 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx373636234775771038951");
			namedStyle59.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle59.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle59.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle60 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx563636234775771497906");
			namedStyle60.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle60.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle60.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle61 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1121636234775772718531");
			namedStyle61.CellType = textCellType31;
			namedStyle61.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle61.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle61.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle61.Renderer = textCellType31;
			namedStyle61.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Bottom;
			namedStyle62 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx2162636234775715798346");
			namedStyle62.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle62.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle62.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle62.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle63 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static4044636234775779046251");
			namedStyle63.CellType = textCellType32;
			namedStyle63.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle63.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle63.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle63.Renderer = textCellType32;
			namedStyle63.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle64 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx2218636234775715886231");
			namedStyle64.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle64.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle64.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle64.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle65 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static34636234775779192726");
			namedStyle65.CellType = textCellType33;
			namedStyle65.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle65.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle65.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle65.Renderer = textCellType33;
			namedStyle65.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle66 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx2424636234775716130356");
			namedStyle66.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Arial", 9F);
			namedStyle66.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle66.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle66.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle67 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx324636234775779680976");
			namedStyle67.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle67.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle67.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle67.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle68 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1132636234775781243376");
			namedStyle68.CellType = textCellType34;
			namedStyle68.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle68.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle68.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle68.Renderer = textCellType34;
			namedStyle68.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Top;
			namedStyle69 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx72636234775779222021");
			namedStyle69.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle69.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle69.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle69.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle70 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1224636234775781360556");
			namedStyle70.CellType = textCellType35;
			namedStyle70.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle70.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle70.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle70.Renderer = textCellType35;
			namedStyle70.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle71 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx1262636234775781399616");
			namedStyle71.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle71.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle71.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle72 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1566636234775781985516");
			namedStyle72.CellType = textCellType36;
			namedStyle72.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle72.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Right;
			namedStyle72.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle72.Renderer = textCellType36;
			namedStyle72.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			namedStyle73 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("BorderEx666636234775780374291");
			namedStyle73.Font = ctx.Resolve<UpgradeHelpers.Helpers.Font>("Microsoft Sans Serif", 7F, UpgradeHelpers.Helpers.FontStyle.Bold);
			namedStyle73.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Center;
			namedStyle73.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle73.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.General;
			namedStyle74 = ctx.Resolve<FarPoint.ViewModels.NamedStyle>("Static1971636234775782708126");
			namedStyle74.CellType = textCellType37;
			namedStyle74.HorizontalAlignment = FarPoint.ViewModels.CellHorizontalAlignment.Left;
			namedStyle74.NoteIndicatorColor = UpgradeHelpers.Helpers.Color.Red;
			namedStyle74.Renderer = textCellType37;
			namedStyle74.VerticalAlignment = FarPoint.ViewModels.CellVerticalAlignment.Center;
			this.Name = "PTSProject.frmTimeCard1";
			IsMdiChild = true;
			this.sprBatt.NamedStyles.Add(namedStyle1);
			this.sprBatt.NamedStyles.Add(namedStyle2);
			this.sprBatt.NamedStyles.Add(namedStyle3);
			this.sprBatt.NamedStyles.Add(namedStyle4);
			this.sprBatt.NamedStyles.Add(namedStyle5);
			this.sprBatt.NamedStyles.Add(namedStyle6);
			this.sprBatt.NamedStyles.Add(namedStyle7);
			this.sprBatt.NamedStyles.Add(namedStyle8);
			this.sprBatt.NamedStyles.Add(namedStyle9);
			this.sprBatt.NamedStyles.Add(namedStyle10);
			this.sprBatt.NamedStyles.Add(namedStyle11);
			this.sprBatt.NamedStyles.Add(namedStyle12);
			this.sprBatt.NamedStyles.Add(namedStyle13);
			this.sprBatt.NamedStyles.Add(namedStyle14);
			this.sprBatt.NamedStyles.Add(namedStyle15);
			this.sprBatt.NamedStyles.Add(namedStyle16);
			this.sprBatt.NamedStyles.Add(namedStyle17);
			this.sprBatt.NamedStyles.Add(namedStyle18);
			this.sprBatt.NamedStyles.Add(namedStyle19);
			this.sprBatt.NamedStyles.Add(namedStyle20);
			this.sprBatt.NamedStyles.Add(namedStyle21);
			this.sprBatt.NamedStyles.Add(namedStyle22);
			this.sprBatt.NamedStyles.Add(namedStyle23);
			this.sprBatt.NamedStyles.Add(namedStyle24);
			this.sprBatt.NamedStyles.Add(namedStyle25);
			this.sprBatt.NamedStyles.Add(namedStyle26);
			this.sprBatt.NamedStyles.Add(namedStyle27);
			this.sprBatt.NamedStyles.Add(namedStyle28);
			this.sprBatt.NamedStyles.Add(namedStyle29);
			this.sprBatt.NamedStyles.Add(namedStyle30);
			this.sprBatt.NamedStyles.Add(namedStyle31);
			this.sprBatt.NamedStyles.Add(namedStyle32);
			this.sprBatt.NamedStyles.Add(namedStyle33);
			this.sprBatt.NamedStyles.Add(namedStyle34);
			this.sprBatt.NamedStyles.Add(namedStyle35);
			this.sprBatt.NamedStyles.Add(namedStyle36);
			this.sprBatt.NamedStyles.Add(namedStyle37);
			this.sprBatt.NamedStyles.Add(namedStyle38);
			this.sprBatt.NamedStyles.Add(namedStyle39);
			this.sprBatt.NamedStyles.Add(namedStyle40);
			this.sprBatt.NamedStyles.Add(namedStyle41);
			this.sprBatt.NamedStyles.Add(namedStyle42);
			this.sprBatt.NamedStyles.Add(namedStyle43);
			this.sprBatt.NamedStyles.Add(namedStyle44);
			this.sprBatt.NamedStyles.Add(namedStyle45);
			this.sprBatt.NamedStyles.Add(namedStyle46);
			this.sprBatt.NamedStyles.Add(namedStyle47);
			this.sprBatt.NamedStyles.Add(namedStyle48);
			this.sprBatt.NamedStyles.Add(namedStyle49);
			this.sprBatt.NamedStyles.Add(namedStyle50);
			this.sprBatt.NamedStyles.Add(namedStyle51);
			this.sprBatt.NamedStyles.Add(namedStyle52);
			this.sprBatt.NamedStyles.Add(namedStyle53);
			this.sprBatt.NamedStyles.Add(namedStyle54);
			this.sprBatt.NamedStyles.Add(namedStyle55);
			this.sprBatt.NamedStyles.Add(namedStyle56);
			this.sprBatt.NamedStyles.Add(namedStyle57);
			this.sprBatt.NamedStyles.Add(namedStyle58);
			this.sprBatt.NamedStyles.Add(namedStyle59);
			this.sprBatt.NamedStyles.Add(namedStyle60);
			this.sprBatt.NamedStyles.Add(namedStyle61);
			this.sprBatt.NamedStyles.Add(namedStyle62);
			this.sprBatt.NamedStyles.Add(namedStyle63);
			this.sprBatt.NamedStyles.Add(namedStyle64);
			this.sprBatt.NamedStyles.Add(namedStyle65);
			this.sprBatt.NamedStyles.Add(namedStyle66);
			this.sprBatt.NamedStyles.Add(namedStyle67);
			this.sprBatt.NamedStyles.Add(namedStyle68);
			this.sprBatt.NamedStyles.Add(namedStyle69);
			this.sprBatt.NamedStyles.Add(namedStyle70);
			this.sprBatt.NamedStyles.Add(namedStyle71);
			this.sprBatt.NamedStyles.Add(namedStyle72);
			this.sprBatt.NamedStyles.Add(namedStyle73);
			this.sprBatt.NamedStyles.Add(namedStyle74);
			this.sprBatt.Sheets.Add(this.sprBatt_Sheet1);
		}

		public virtual FarPoint.ViewModels.FpSpreadViewModel sprBatt { get; set; }

		public virtual WNFRMS.Viewmodels.DateTimePickerViewModel calDate { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.LabelViewModel Label1 { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual FarPoint.ViewModels.SheetViewModel sprBatt_Sheet1 { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdPrintAll { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdLeave { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdExcept { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdClose { get; set; }

		public virtual UpgradeHelpers.BasicViewModels.ButtonViewModel cmdPrint { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Int32 FirstTime { get; set; }

		[UpgradeHelpers.Helpers.StateManagement(UpgradeHelpers.Helpers.StateManagementValues.ServerOnly)]
		public virtual System.Boolean IsDisposed { get; set; }

		public virtual bool IsMdiChild { get; set; }

	}

}